//
// Money
//
// Copyright (c) 2015-2017 Daniel Thorpe
//
// Money is licensed under the MIT License. Read the full license at
// https://github.com/danthorpe/Money/blob/master/LICENSE
//
// Autogenerated from build scripts, do not manually edit this file.
//

// MARK: - Currencies

extension Currency {

   /// Currency ADP
   public final class ADP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ADP
      public static let shared = ADP(code: "ADP")
   }

   /// Currency AED
   public final class AED: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AED
      public static let shared = AED(code: "AED")
   }

   /// Currency AFA
   public final class AFA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AFA
      public static let shared = AFA(code: "AFA")
   }

   /// Currency AFN
   public final class AFN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AFN
      public static let shared = AFN(code: "AFN")
   }

   /// Currency ALK
   public final class ALK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ALK
      public static let shared = ALK(code: "ALK")
   }

   /// Currency ALL
   public final class ALL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ALL
      public static let shared = ALL(code: "ALL")
   }

   /// Currency AMD
   public final class AMD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AMD
      public static let shared = AMD(code: "AMD")
   }

   /// Currency ANG
   public final class ANG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ANG
      public static let shared = ANG(code: "ANG")
   }

   /// Currency AOA
   public final class AOA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AOA
      public static let shared = AOA(code: "AOA")
   }

   /// Currency AOK
   public final class AOK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AOK
      public static let shared = AOK(code: "AOK")
   }

   /// Currency AON
   public final class AON: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AON
      public static let shared = AON(code: "AON")
   }

   /// Currency AOR
   public final class AOR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AOR
      public static let shared = AOR(code: "AOR")
   }

   /// Currency ARA
   public final class ARA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ARA
      public static let shared = ARA(code: "ARA")
   }

   /// Currency ARL
   public final class ARL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ARL
      public static let shared = ARL(code: "ARL")
   }

   /// Currency ARM
   public final class ARM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ARM
      public static let shared = ARM(code: "ARM")
   }

   /// Currency ARP
   public final class ARP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ARP
      public static let shared = ARP(code: "ARP")
   }

   /// Currency ARS
   public final class ARS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ARS
      public static let shared = ARS(code: "ARS")
   }

   /// Currency ATS
   public final class ATS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ATS
      public static let shared = ATS(code: "ATS")
   }

   /// Currency AUD
   public final class AUD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AUD
      public static let shared = AUD(code: "AUD")
   }

   /// Currency AWG
   public final class AWG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AWG
      public static let shared = AWG(code: "AWG")
   }

   /// Currency AZM
   public final class AZM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AZM
      public static let shared = AZM(code: "AZM")
   }

   /// Currency AZN
   public final class AZN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.AZN
      public static let shared = AZN(code: "AZN")
   }

   /// Currency BAD
   public final class BAD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BAD
      public static let shared = BAD(code: "BAD")
   }

   /// Currency BAM
   public final class BAM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BAM
      public static let shared = BAM(code: "BAM")
   }

   /// Currency BAN
   public final class BAN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BAN
      public static let shared = BAN(code: "BAN")
   }

   /// Currency BBD
   public final class BBD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BBD
      public static let shared = BBD(code: "BBD")
   }

   /// Currency BDT
   public final class BDT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BDT
      public static let shared = BDT(code: "BDT")
   }

   /// Currency BEC
   public final class BEC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BEC
      public static let shared = BEC(code: "BEC")
   }

   /// Currency BEF
   public final class BEF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BEF
      public static let shared = BEF(code: "BEF")
   }

   /// Currency BEL
   public final class BEL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BEL
      public static let shared = BEL(code: "BEL")
   }

   /// Currency BGL
   public final class BGL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BGL
      public static let shared = BGL(code: "BGL")
   }

   /// Currency BGM
   public final class BGM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BGM
      public static let shared = BGM(code: "BGM")
   }

   /// Currency BGN
   public final class BGN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BGN
      public static let shared = BGN(code: "BGN")
   }

   /// Currency BGO
   public final class BGO: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BGO
      public static let shared = BGO(code: "BGO")
   }

   /// Currency BHD
   public final class BHD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BHD
      public static let shared = BHD(code: "BHD")
   }

   /// Currency BIF
   public final class BIF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BIF
      public static let shared = BIF(code: "BIF")
   }

   /// Currency BMD
   public final class BMD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BMD
      public static let shared = BMD(code: "BMD")
   }

   /// Currency BND
   public final class BND: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BND
      public static let shared = BND(code: "BND")
   }

   /// Currency BOB
   public final class BOB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BOB
      public static let shared = BOB(code: "BOB")
   }

   /// Currency BOL
   public final class BOL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BOL
      public static let shared = BOL(code: "BOL")
   }

   /// Currency BOP
   public final class BOP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BOP
      public static let shared = BOP(code: "BOP")
   }

   /// Currency BOV
   public final class BOV: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BOV
      public static let shared = BOV(code: "BOV")
   }

   /// Currency BRB
   public final class BRB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRB
      public static let shared = BRB(code: "BRB")
   }

   /// Currency BRC
   public final class BRC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRC
      public static let shared = BRC(code: "BRC")
   }

   /// Currency BRE
   public final class BRE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRE
      public static let shared = BRE(code: "BRE")
   }

   /// Currency BRL
   public final class BRL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRL
      public static let shared = BRL(code: "BRL")
   }

   /// Currency BRN
   public final class BRN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRN
      public static let shared = BRN(code: "BRN")
   }

   /// Currency BRR
   public final class BRR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRR
      public static let shared = BRR(code: "BRR")
   }

   /// Currency BRZ
   public final class BRZ: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BRZ
      public static let shared = BRZ(code: "BRZ")
   }

   /// Currency BSD
   public final class BSD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BSD
      public static let shared = BSD(code: "BSD")
   }

   /// Currency BTN
   public final class BTN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BTN
      public static let shared = BTN(code: "BTN")
   }

   /// Currency BUK
   public final class BUK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BUK
      public static let shared = BUK(code: "BUK")
   }

   /// Currency BWP
   public final class BWP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BWP
      public static let shared = BWP(code: "BWP")
   }

   /// Currency BYB
   public final class BYB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BYB
      public static let shared = BYB(code: "BYB")
   }

   /// Currency BYR
   public final class BYR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BYR
      public static let shared = BYR(code: "BYR")
   }

   /// Currency BZD
   public final class BZD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.BZD
      public static let shared = BZD(code: "BZD")
   }

   /// Currency CAD
   public final class CAD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CAD
      public static let shared = CAD(code: "CAD")
   }

   /// Currency CDF
   public final class CDF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CDF
      public static let shared = CDF(code: "CDF")
   }

   /// Currency CHE
   public final class CHE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CHE
      public static let shared = CHE(code: "CHE")
   }

   /// Currency CHF
   public final class CHF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CHF
      public static let shared = CHF(code: "CHF")
   }

   /// Currency CHW
   public final class CHW: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CHW
      public static let shared = CHW(code: "CHW")
   }

   /// Currency CLE
   public final class CLE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CLE
      public static let shared = CLE(code: "CLE")
   }

   /// Currency CLF
   public final class CLF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CLF
      public static let shared = CLF(code: "CLF")
   }

   /// Currency CLP
   public final class CLP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CLP
      public static let shared = CLP(code: "CLP")
   }

   /// Currency CNX
   public final class CNX: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CNX
      public static let shared = CNX(code: "CNX")
   }

   /// Currency CNY
   public final class CNY: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CNY
      public static let shared = CNY(code: "CNY")
   }

   /// Currency COP
   public final class COP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.COP
      public static let shared = COP(code: "COP")
   }

   /// Currency COU
   public final class COU: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.COU
      public static let shared = COU(code: "COU")
   }

   /// Currency CRC
   public final class CRC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CRC
      public static let shared = CRC(code: "CRC")
   }

   /// Currency CSD
   public final class CSD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CSD
      public static let shared = CSD(code: "CSD")
   }

   /// Currency CSK
   public final class CSK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CSK
      public static let shared = CSK(code: "CSK")
   }

   /// Currency CUC
   public final class CUC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CUC
      public static let shared = CUC(code: "CUC")
   }

   /// Currency CUP
   public final class CUP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CUP
      public static let shared = CUP(code: "CUP")
   }

   /// Currency CVE
   public final class CVE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CVE
      public static let shared = CVE(code: "CVE")
   }

   /// Currency CYP
   public final class CYP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CYP
      public static let shared = CYP(code: "CYP")
   }

   /// Currency CZK
   public final class CZK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.CZK
      public static let shared = CZK(code: "CZK")
   }

   /// Currency DDM
   public final class DDM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.DDM
      public static let shared = DDM(code: "DDM")
   }

   /// Currency DEM
   public final class DEM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.DEM
      public static let shared = DEM(code: "DEM")
   }

   /// Currency DJF
   public final class DJF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.DJF
      public static let shared = DJF(code: "DJF")
   }

   /// Currency DKK
   public final class DKK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.DKK
      public static let shared = DKK(code: "DKK")
   }

   /// Currency DOP
   public final class DOP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.DOP
      public static let shared = DOP(code: "DOP")
   }

   /// Currency DZD
   public final class DZD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.DZD
      public static let shared = DZD(code: "DZD")
   }

   /// Currency ECS
   public final class ECS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ECS
      public static let shared = ECS(code: "ECS")
   }

   /// Currency ECV
   public final class ECV: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ECV
      public static let shared = ECV(code: "ECV")
   }

   /// Currency EEK
   public final class EEK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.EEK
      public static let shared = EEK(code: "EEK")
   }

   /// Currency EGP
   public final class EGP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.EGP
      public static let shared = EGP(code: "EGP")
   }

   /// Currency EQE
   public final class EQE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.EQE
      public static let shared = EQE(code: "EQE")
   }

   /// Currency ERN
   public final class ERN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ERN
      public static let shared = ERN(code: "ERN")
   }

   /// Currency ESA
   public final class ESA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ESA
      public static let shared = ESA(code: "ESA")
   }

   /// Currency ESB
   public final class ESB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ESB
      public static let shared = ESB(code: "ESB")
   }

   /// Currency ESP
   public final class ESP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ESP
      public static let shared = ESP(code: "ESP")
   }

   /// Currency ETB
   public final class ETB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ETB
      public static let shared = ETB(code: "ETB")
   }

   /// Currency EUR
   public final class EUR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.EUR
      public static let shared = EUR(code: "EUR")
   }

   /// Currency FIM
   public final class FIM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.FIM
      public static let shared = FIM(code: "FIM")
   }

   /// Currency FJD
   public final class FJD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.FJD
      public static let shared = FJD(code: "FJD")
   }

   /// Currency FKP
   public final class FKP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.FKP
      public static let shared = FKP(code: "FKP")
   }

   /// Currency FRF
   public final class FRF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.FRF
      public static let shared = FRF(code: "FRF")
   }

   /// Currency GBP
   public final class GBP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GBP
      public static let shared = GBP(code: "GBP")
   }

   /// Currency GEK
   public final class GEK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GEK
      public static let shared = GEK(code: "GEK")
   }

   /// Currency GEL
   public final class GEL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GEL
      public static let shared = GEL(code: "GEL")
   }

   /// Currency GHC
   public final class GHC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GHC
      public static let shared = GHC(code: "GHC")
   }

   /// Currency GHS
   public final class GHS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GHS
      public static let shared = GHS(code: "GHS")
   }

   /// Currency GIP
   public final class GIP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GIP
      public static let shared = GIP(code: "GIP")
   }

   /// Currency GMD
   public final class GMD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GMD
      public static let shared = GMD(code: "GMD")
   }

   /// Currency GNF
   public final class GNF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GNF
      public static let shared = GNF(code: "GNF")
   }

   /// Currency GNS
   public final class GNS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GNS
      public static let shared = GNS(code: "GNS")
   }

   /// Currency GQE
   public final class GQE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GQE
      public static let shared = GQE(code: "GQE")
   }

   /// Currency GRD
   public final class GRD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GRD
      public static let shared = GRD(code: "GRD")
   }

   /// Currency GTQ
   public final class GTQ: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GTQ
      public static let shared = GTQ(code: "GTQ")
   }

   /// Currency GWE
   public final class GWE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GWE
      public static let shared = GWE(code: "GWE")
   }

   /// Currency GWP
   public final class GWP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GWP
      public static let shared = GWP(code: "GWP")
   }

   /// Currency GYD
   public final class GYD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.GYD
      public static let shared = GYD(code: "GYD")
   }

   /// Currency HKD
   public final class HKD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.HKD
      public static let shared = HKD(code: "HKD")
   }

   /// Currency HNL
   public final class HNL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.HNL
      public static let shared = HNL(code: "HNL")
   }

   /// Currency HRD
   public final class HRD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.HRD
      public static let shared = HRD(code: "HRD")
   }

   /// Currency HRK
   public final class HRK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.HRK
      public static let shared = HRK(code: "HRK")
   }

   /// Currency HTG
   public final class HTG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.HTG
      public static let shared = HTG(code: "HTG")
   }

   /// Currency HUF
   public final class HUF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.HUF
      public static let shared = HUF(code: "HUF")
   }

   /// Currency IDR
   public final class IDR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.IDR
      public static let shared = IDR(code: "IDR")
   }

   /// Currency IEP
   public final class IEP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.IEP
      public static let shared = IEP(code: "IEP")
   }

   /// Currency ILP
   public final class ILP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ILP
      public static let shared = ILP(code: "ILP")
   }

   /// Currency ILR
   public final class ILR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ILR
      public static let shared = ILR(code: "ILR")
   }

   /// Currency ILS
   public final class ILS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ILS
      public static let shared = ILS(code: "ILS")
   }

   /// Currency INR
   public final class INR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.INR
      public static let shared = INR(code: "INR")
   }

   /// Currency IQD
   public final class IQD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.IQD
      public static let shared = IQD(code: "IQD")
   }

   /// Currency IRR
   public final class IRR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.IRR
      public static let shared = IRR(code: "IRR")
   }

   /// Currency ISJ
   public final class ISJ: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ISJ
      public static let shared = ISJ(code: "ISJ")
   }

   /// Currency ISK
   public final class ISK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ISK
      public static let shared = ISK(code: "ISK")
   }

   /// Currency ITL
   public final class ITL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ITL
      public static let shared = ITL(code: "ITL")
   }

   /// Currency JMD
   public final class JMD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.JMD
      public static let shared = JMD(code: "JMD")
   }

   /// Currency JOD
   public final class JOD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.JOD
      public static let shared = JOD(code: "JOD")
   }

   /// Currency JPY
   public final class JPY: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.JPY
      public static let shared = JPY(code: "JPY")
   }

   /// Currency KES
   public final class KES: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KES
      public static let shared = KES(code: "KES")
   }

   /// Currency KGS
   public final class KGS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KGS
      public static let shared = KGS(code: "KGS")
   }

   /// Currency KHR
   public final class KHR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KHR
      public static let shared = KHR(code: "KHR")
   }

   /// Currency KMF
   public final class KMF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KMF
      public static let shared = KMF(code: "KMF")
   }

   /// Currency KPW
   public final class KPW: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KPW
      public static let shared = KPW(code: "KPW")
   }

   /// Currency KRH
   public final class KRH: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KRH
      public static let shared = KRH(code: "KRH")
   }

   /// Currency KRO
   public final class KRO: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KRO
      public static let shared = KRO(code: "KRO")
   }

   /// Currency KRW
   public final class KRW: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KRW
      public static let shared = KRW(code: "KRW")
   }

   /// Currency KWD
   public final class KWD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KWD
      public static let shared = KWD(code: "KWD")
   }

   /// Currency KYD
   public final class KYD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KYD
      public static let shared = KYD(code: "KYD")
   }

   /// Currency KZT
   public final class KZT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.KZT
      public static let shared = KZT(code: "KZT")
   }

   /// Currency LAK
   public final class LAK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LAK
      public static let shared = LAK(code: "LAK")
   }

   /// Currency LBP
   public final class LBP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LBP
      public static let shared = LBP(code: "LBP")
   }

   /// Currency LKR
   public final class LKR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LKR
      public static let shared = LKR(code: "LKR")
   }

   /// Currency LRD
   public final class LRD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LRD
      public static let shared = LRD(code: "LRD")
   }

   /// Currency LSL
   public final class LSL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LSL
      public static let shared = LSL(code: "LSL")
   }

   /// Currency LSM
   public final class LSM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LSM
      public static let shared = LSM(code: "LSM")
   }

   /// Currency LTL
   public final class LTL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LTL
      public static let shared = LTL(code: "LTL")
   }

   /// Currency LTT
   public final class LTT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LTT
      public static let shared = LTT(code: "LTT")
   }

   /// Currency LUC
   public final class LUC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LUC
      public static let shared = LUC(code: "LUC")
   }

   /// Currency LUF
   public final class LUF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LUF
      public static let shared = LUF(code: "LUF")
   }

   /// Currency LUL
   public final class LUL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LUL
      public static let shared = LUL(code: "LUL")
   }

   /// Currency LVL
   public final class LVL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LVL
      public static let shared = LVL(code: "LVL")
   }

   /// Currency LVR
   public final class LVR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LVR
      public static let shared = LVR(code: "LVR")
   }

   /// Currency LYD
   public final class LYD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.LYD
      public static let shared = LYD(code: "LYD")
   }

   /// Currency MAD
   public final class MAD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MAD
      public static let shared = MAD(code: "MAD")
   }

   /// Currency MAF
   public final class MAF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MAF
      public static let shared = MAF(code: "MAF")
   }

   /// Currency MCF
   public final class MCF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MCF
      public static let shared = MCF(code: "MCF")
   }

   /// Currency MDC
   public final class MDC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MDC
      public static let shared = MDC(code: "MDC")
   }

   /// Currency MDL
   public final class MDL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MDL
      public static let shared = MDL(code: "MDL")
   }

   /// Currency MGA
   public final class MGA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MGA
      public static let shared = MGA(code: "MGA")
   }

   /// Currency MGF
   public final class MGF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MGF
      public static let shared = MGF(code: "MGF")
   }

   /// Currency MKD
   public final class MKD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MKD
      public static let shared = MKD(code: "MKD")
   }

   /// Currency MKN
   public final class MKN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MKN
      public static let shared = MKN(code: "MKN")
   }

   /// Currency MLF
   public final class MLF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MLF
      public static let shared = MLF(code: "MLF")
   }

   /// Currency MMK
   public final class MMK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MMK
      public static let shared = MMK(code: "MMK")
   }

   /// Currency MNT
   public final class MNT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MNT
      public static let shared = MNT(code: "MNT")
   }

   /// Currency MOP
   public final class MOP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MOP
      public static let shared = MOP(code: "MOP")
   }

   /// Currency MRO
   public final class MRO: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MRO
      public static let shared = MRO(code: "MRO")
   }

   /// Currency MTL
   public final class MTL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MTL
      public static let shared = MTL(code: "MTL")
   }

   /// Currency MTP
   public final class MTP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MTP
      public static let shared = MTP(code: "MTP")
   }

   /// Currency MUR
   public final class MUR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MUR
      public static let shared = MUR(code: "MUR")
   }

   /// Currency MVP
   public final class MVP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MVP
      public static let shared = MVP(code: "MVP")
   }

   /// Currency MVR
   public final class MVR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MVR
      public static let shared = MVR(code: "MVR")
   }

   /// Currency MWK
   public final class MWK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MWK
      public static let shared = MWK(code: "MWK")
   }

   /// Currency MXN
   public final class MXN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MXN
      public static let shared = MXN(code: "MXN")
   }

   /// Currency MXP
   public final class MXP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MXP
      public static let shared = MXP(code: "MXP")
   }

   /// Currency MXV
   public final class MXV: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MXV
      public static let shared = MXV(code: "MXV")
   }

   /// Currency MYR
   public final class MYR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MYR
      public static let shared = MYR(code: "MYR")
   }

   /// Currency MZE
   public final class MZE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MZE
      public static let shared = MZE(code: "MZE")
   }

   /// Currency MZM
   public final class MZM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MZM
      public static let shared = MZM(code: "MZM")
   }

   /// Currency MZN
   public final class MZN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.MZN
      public static let shared = MZN(code: "MZN")
   }

   /// Currency NAD
   public final class NAD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NAD
      public static let shared = NAD(code: "NAD")
   }

   /// Currency NGN
   public final class NGN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NGN
      public static let shared = NGN(code: "NGN")
   }

   /// Currency NIC
   public final class NIC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NIC
      public static let shared = NIC(code: "NIC")
   }

   /// Currency NIO
   public final class NIO: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NIO
      public static let shared = NIO(code: "NIO")
   }

   /// Currency NLG
   public final class NLG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NLG
      public static let shared = NLG(code: "NLG")
   }

   /// Currency NOK
   public final class NOK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NOK
      public static let shared = NOK(code: "NOK")
   }

   /// Currency NPR
   public final class NPR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NPR
      public static let shared = NPR(code: "NPR")
   }

   /// Currency NZD
   public final class NZD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.NZD
      public static let shared = NZD(code: "NZD")
   }

   /// Currency OMR
   public final class OMR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.OMR
      public static let shared = OMR(code: "OMR")
   }

   /// Currency PAB
   public final class PAB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PAB
      public static let shared = PAB(code: "PAB")
   }

   /// Currency PEI
   public final class PEI: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PEI
      public static let shared = PEI(code: "PEI")
   }

   /// Currency PEN
   public final class PEN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PEN
      public static let shared = PEN(code: "PEN")
   }

   /// Currency PES
   public final class PES: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PES
      public static let shared = PES(code: "PES")
   }

   /// Currency PGK
   public final class PGK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PGK
      public static let shared = PGK(code: "PGK")
   }

   /// Currency PHP
   public final class PHP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PHP
      public static let shared = PHP(code: "PHP")
   }

   /// Currency PKR
   public final class PKR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PKR
      public static let shared = PKR(code: "PKR")
   }

   /// Currency PLN
   public final class PLN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PLN
      public static let shared = PLN(code: "PLN")
   }

   /// Currency PLZ
   public final class PLZ: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PLZ
      public static let shared = PLZ(code: "PLZ")
   }

   /// Currency PTE
   public final class PTE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PTE
      public static let shared = PTE(code: "PTE")
   }

   /// Currency PYG
   public final class PYG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.PYG
      public static let shared = PYG(code: "PYG")
   }

   /// Currency QAR
   public final class QAR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.QAR
      public static let shared = QAR(code: "QAR")
   }

   /// Currency RHD
   public final class RHD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.RHD
      public static let shared = RHD(code: "RHD")
   }

   /// Currency ROL
   public final class ROL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ROL
      public static let shared = ROL(code: "ROL")
   }

   /// Currency RON
   public final class RON: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.RON
      public static let shared = RON(code: "RON")
   }

   /// Currency RSD
   public final class RSD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.RSD
      public static let shared = RSD(code: "RSD")
   }

   /// Currency RUB
   public final class RUB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.RUB
      public static let shared = RUB(code: "RUB")
   }

   /// Currency RUR
   public final class RUR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.RUR
      public static let shared = RUR(code: "RUR")
   }

   /// Currency RWF
   public final class RWF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.RWF
      public static let shared = RWF(code: "RWF")
   }

   /// Currency SAR
   public final class SAR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SAR
      public static let shared = SAR(code: "SAR")
   }

   /// Currency SBD
   public final class SBD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SBD
      public static let shared = SBD(code: "SBD")
   }

   /// Currency SCR
   public final class SCR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SCR
      public static let shared = SCR(code: "SCR")
   }

   /// Currency SDD
   public final class SDD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SDD
      public static let shared = SDD(code: "SDD")
   }

   /// Currency SDG
   public final class SDG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SDG
      public static let shared = SDG(code: "SDG")
   }

   /// Currency SDP
   public final class SDP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SDP
      public static let shared = SDP(code: "SDP")
   }

   /// Currency SEK
   public final class SEK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SEK
      public static let shared = SEK(code: "SEK")
   }

   /// Currency SGD
   public final class SGD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SGD
      public static let shared = SGD(code: "SGD")
   }

   /// Currency SHP
   public final class SHP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SHP
      public static let shared = SHP(code: "SHP")
   }

   /// Currency SIT
   public final class SIT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SIT
      public static let shared = SIT(code: "SIT")
   }

   /// Currency SKK
   public final class SKK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SKK
      public static let shared = SKK(code: "SKK")
   }

   /// Currency SLL
   public final class SLL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SLL
      public static let shared = SLL(code: "SLL")
   }

   /// Currency SOS
   public final class SOS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SOS
      public static let shared = SOS(code: "SOS")
   }

   /// Currency SRD
   public final class SRD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SRD
      public static let shared = SRD(code: "SRD")
   }

   /// Currency SRG
   public final class SRG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SRG
      public static let shared = SRG(code: "SRG")
   }

   /// Currency SSP
   public final class SSP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SSP
      public static let shared = SSP(code: "SSP")
   }

   /// Currency STD
   public final class STD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.STD
      public static let shared = STD(code: "STD")
   }

   /// Currency SUR
   public final class SUR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SUR
      public static let shared = SUR(code: "SUR")
   }

   /// Currency SVC
   public final class SVC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SVC
      public static let shared = SVC(code: "SVC")
   }

   /// Currency SYP
   public final class SYP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SYP
      public static let shared = SYP(code: "SYP")
   }

   /// Currency SZL
   public final class SZL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.SZL
      public static let shared = SZL(code: "SZL")
   }

   /// Currency THB
   public final class THB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.THB
      public static let shared = THB(code: "THB")
   }

   /// Currency TJR
   public final class TJR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TJR
      public static let shared = TJR(code: "TJR")
   }

   /// Currency TJS
   public final class TJS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TJS
      public static let shared = TJS(code: "TJS")
   }

   /// Currency TMM
   public final class TMM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TMM
      public static let shared = TMM(code: "TMM")
   }

   /// Currency TMT
   public final class TMT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TMT
      public static let shared = TMT(code: "TMT")
   }

   /// Currency TND
   public final class TND: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TND
      public static let shared = TND(code: "TND")
   }

   /// Currency TOP
   public final class TOP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TOP
      public static let shared = TOP(code: "TOP")
   }

   /// Currency TPE
   public final class TPE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TPE
      public static let shared = TPE(code: "TPE")
   }

   /// Currency TRL
   public final class TRL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TRL
      public static let shared = TRL(code: "TRL")
   }

   /// Currency TRY
   public final class TRY: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TRY
      public static let shared = TRY(code: "TRY")
   }

   /// Currency TTD
   public final class TTD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TTD
      public static let shared = TTD(code: "TTD")
   }

   /// Currency TWD
   public final class TWD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TWD
      public static let shared = TWD(code: "TWD")
   }

   /// Currency TZS
   public final class TZS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.TZS
      public static let shared = TZS(code: "TZS")
   }

   /// Currency UAH
   public final class UAH: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UAH
      public static let shared = UAH(code: "UAH")
   }

   /// Currency UAK
   public final class UAK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UAK
      public static let shared = UAK(code: "UAK")
   }

   /// Currency UGS
   public final class UGS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UGS
      public static let shared = UGS(code: "UGS")
   }

   /// Currency UGX
   public final class UGX: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UGX
      public static let shared = UGX(code: "UGX")
   }

   /// Currency USD
   public final class USD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.USD
      public static let shared = USD(code: "USD")
   }

   /// Currency USN
   public final class USN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.USN
      public static let shared = USN(code: "USN")
   }

   /// Currency USS
   public final class USS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.USS
      public static let shared = USS(code: "USS")
   }

   /// Currency UYI
   public final class UYI: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UYI
      public static let shared = UYI(code: "UYI")
   }

   /// Currency UYP
   public final class UYP: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UYP
      public static let shared = UYP(code: "UYP")
   }

   /// Currency UYU
   public final class UYU: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UYU
      public static let shared = UYU(code: "UYU")
   }

   /// Currency UZS
   public final class UZS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.UZS
      public static let shared = UZS(code: "UZS")
   }

   /// Currency VEB
   public final class VEB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.VEB
      public static let shared = VEB(code: "VEB")
   }

   /// Currency VEF
   public final class VEF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.VEF
      public static let shared = VEF(code: "VEF")
   }

   /// Currency VND
   public final class VND: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.VND
      public static let shared = VND(code: "VND")
   }

   /// Currency VNN
   public final class VNN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.VNN
      public static let shared = VNN(code: "VNN")
   }

   /// Currency VUV
   public final class VUV: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.VUV
      public static let shared = VUV(code: "VUV")
   }

   /// Currency WST
   public final class WST: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.WST
      public static let shared = WST(code: "WST")
   }

   /// Currency XAF
   public final class XAF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XAF
      public static let shared = XAF(code: "XAF")
   }

   /// Currency XAG
   public final class XAG: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XAG
      public static let shared = XAG(code: "XAG")
   }

   /// Currency XAU
   public final class XAU: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XAU
      public static let shared = XAU(code: "XAU")
   }

   /// Currency XBA
   public final class XBA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XBA
      public static let shared = XBA(code: "XBA")
   }

   /// Currency XBB
   public final class XBB: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XBB
      public static let shared = XBB(code: "XBB")
   }

   /// Currency XBC
   public final class XBC: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XBC
      public static let shared = XBC(code: "XBC")
   }

   /// Currency XBD
   public final class XBD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XBD
      public static let shared = XBD(code: "XBD")
   }

   /// Currency XCD
   public final class XCD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XCD
      public static let shared = XCD(code: "XCD")
   }

   /// Currency XDR
   public final class XDR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XDR
      public static let shared = XDR(code: "XDR")
   }

   /// Currency XEU
   public final class XEU: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XEU
      public static let shared = XEU(code: "XEU")
   }

   /// Currency XFO
   public final class XFO: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XFO
      public static let shared = XFO(code: "XFO")
   }

   /// Currency XFU
   public final class XFU: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XFU
      public static let shared = XFU(code: "XFU")
   }

   /// Currency XOF
   public final class XOF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XOF
      public static let shared = XOF(code: "XOF")
   }

   /// Currency XPD
   public final class XPD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XPD
      public static let shared = XPD(code: "XPD")
   }

   /// Currency XPF
   public final class XPF: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XPF
      public static let shared = XPF(code: "XPF")
   }

   /// Currency XPT
   public final class XPT: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XPT
      public static let shared = XPT(code: "XPT")
   }

   /// Currency XRE
   public final class XRE: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XRE
      public static let shared = XRE(code: "XRE")
   }

   /// Currency XSU
   public final class XSU: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XSU
      public static let shared = XSU(code: "XSU")
   }

   /// Currency XTS
   public final class XTS: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XTS
      public static let shared = XTS(code: "XTS")
   }

   /// Currency XUA
   public final class XUA: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XUA
      public static let shared = XUA(code: "XUA")
   }

   /// Currency XXX
   public final class XXX: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.XXX
      public static let shared = XXX(code: "XXX")
   }

   /// Currency YDD
   public final class YDD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.YDD
      public static let shared = YDD(code: "YDD")
   }

   /// Currency YER
   public final class YER: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.YER
      public static let shared = YER(code: "YER")
   }

   /// Currency YUD
   public final class YUD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.YUD
      public static let shared = YUD(code: "YUD")
   }

   /// Currency YUM
   public final class YUM: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.YUM
      public static let shared = YUM(code: "YUM")
   }

   /// Currency YUN
   public final class YUN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.YUN
      public static let shared = YUN(code: "YUN")
   }

   /// Currency YUR
   public final class YUR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.YUR
      public static let shared = YUR(code: "YUR")
   }

   /// Currency ZAL
   public final class ZAL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZAL
      public static let shared = ZAL(code: "ZAL")
   }

   /// Currency ZAR
   public final class ZAR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZAR
      public static let shared = ZAR(code: "ZAR")
   }

   /// Currency ZMK
   public final class ZMK: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZMK
      public static let shared = ZMK(code: "ZMK")
   }

   /// Currency ZMW
   public final class ZMW: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZMW
      public static let shared = ZMW(code: "ZMW")
   }

   /// Currency ZRN
   public final class ZRN: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZRN
      public static let shared = ZRN(code: "ZRN")
   }

   /// Currency ZRZ
   public final class ZRZ: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZRZ
      public static let shared = ZRZ(code: "ZRZ")
   }

   /// Currency ZWL
   public final class ZWL: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZWL
      public static let shared = ZWL(code: "ZWL")
   }

   /// Currency ZWR
   public final class ZWR: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZWR
      public static let shared = ZWR(code: "ZWR")
   }

   /// Currency ZWD
   public final class ZWD: BaseCurrency, ISOCurrencyProtocol {
      /// - returns: shared instance for Currency.ZWD
      public static let shared = ZWD(code: "ZWD")
   }
}

// MARK: - Money



/// ADP Money
public typealias ADP = ISOMoney<Currency.ADP>

/// AED Money
public typealias AED = ISOMoney<Currency.AED>

/// AFA Money
public typealias AFA = ISOMoney<Currency.AFA>

/// AFN Money
public typealias AFN = ISOMoney<Currency.AFN>

/// ALK Money
public typealias ALK = ISOMoney<Currency.ALK>

/// ALL Money
public typealias ALL = ISOMoney<Currency.ALL>

/// AMD Money
public typealias AMD = ISOMoney<Currency.AMD>

/// ANG Money
public typealias ANG = ISOMoney<Currency.ANG>

/// AOA Money
public typealias AOA = ISOMoney<Currency.AOA>

/// AOK Money
public typealias AOK = ISOMoney<Currency.AOK>

/// AON Money
public typealias AON = ISOMoney<Currency.AON>

/// AOR Money
public typealias AOR = ISOMoney<Currency.AOR>

/// ARA Money
public typealias ARA = ISOMoney<Currency.ARA>

/// ARL Money
public typealias ARL = ISOMoney<Currency.ARL>

/// ARM Money
public typealias ARM = ISOMoney<Currency.ARM>

/// ARP Money
public typealias ARP = ISOMoney<Currency.ARP>

/// ARS Money
public typealias ARS = ISOMoney<Currency.ARS>

/// ATS Money
public typealias ATS = ISOMoney<Currency.ATS>

/// AUD Money
public typealias AUD = ISOMoney<Currency.AUD>

/// AWG Money
public typealias AWG = ISOMoney<Currency.AWG>

/// AZM Money
public typealias AZM = ISOMoney<Currency.AZM>

/// AZN Money
public typealias AZN = ISOMoney<Currency.AZN>

/// BAD Money
public typealias BAD = ISOMoney<Currency.BAD>

/// BAM Money
public typealias BAM = ISOMoney<Currency.BAM>

/// BAN Money
public typealias BAN = ISOMoney<Currency.BAN>

/// BBD Money
public typealias BBD = ISOMoney<Currency.BBD>

/// BDT Money
public typealias BDT = ISOMoney<Currency.BDT>

/// BEC Money
public typealias BEC = ISOMoney<Currency.BEC>

/// BEF Money
public typealias BEF = ISOMoney<Currency.BEF>

/// BEL Money
public typealias BEL = ISOMoney<Currency.BEL>

/// BGL Money
public typealias BGL = ISOMoney<Currency.BGL>

/// BGM Money
public typealias BGM = ISOMoney<Currency.BGM>

/// BGN Money
public typealias BGN = ISOMoney<Currency.BGN>

/// BGO Money
public typealias BGO = ISOMoney<Currency.BGO>

/// BHD Money
public typealias BHD = ISOMoney<Currency.BHD>

/// BIF Money
public typealias BIF = ISOMoney<Currency.BIF>

/// BMD Money
public typealias BMD = ISOMoney<Currency.BMD>

/// BND Money
public typealias BND = ISOMoney<Currency.BND>

/// BOB Money
public typealias BOB = ISOMoney<Currency.BOB>

/// BOL Money
public typealias BOL = ISOMoney<Currency.BOL>

/// BOP Money
public typealias BOP = ISOMoney<Currency.BOP>

/// BOV Money
public typealias BOV = ISOMoney<Currency.BOV>

/// BRB Money
public typealias BRB = ISOMoney<Currency.BRB>

/// BRC Money
public typealias BRC = ISOMoney<Currency.BRC>

/// BRE Money
public typealias BRE = ISOMoney<Currency.BRE>

/// BRL Money
public typealias BRL = ISOMoney<Currency.BRL>

/// BRN Money
public typealias BRN = ISOMoney<Currency.BRN>

/// BRR Money
public typealias BRR = ISOMoney<Currency.BRR>

/// BRZ Money
public typealias BRZ = ISOMoney<Currency.BRZ>

/// BSD Money
public typealias BSD = ISOMoney<Currency.BSD>

/// BTN Money
public typealias BTN = ISOMoney<Currency.BTN>

/// BUK Money
public typealias BUK = ISOMoney<Currency.BUK>

/// BWP Money
public typealias BWP = ISOMoney<Currency.BWP>

/// BYB Money
public typealias BYB = ISOMoney<Currency.BYB>

/// BYR Money
public typealias BYR = ISOMoney<Currency.BYR>

/// BZD Money
public typealias BZD = ISOMoney<Currency.BZD>

/// CAD Money
public typealias CAD = ISOMoney<Currency.CAD>

/// CDF Money
public typealias CDF = ISOMoney<Currency.CDF>

/// CHE Money
public typealias CHE = ISOMoney<Currency.CHE>

/// CHF Money
public typealias CHF = ISOMoney<Currency.CHF>

/// CHW Money
public typealias CHW = ISOMoney<Currency.CHW>

/// CLE Money
public typealias CLE = ISOMoney<Currency.CLE>

/// CLF Money
public typealias CLF = ISOMoney<Currency.CLF>

/// CLP Money
public typealias CLP = ISOMoney<Currency.CLP>

/// CNX Money
public typealias CNX = ISOMoney<Currency.CNX>

/// CNY Money
public typealias CNY = ISOMoney<Currency.CNY>

/// COP Money
public typealias COP = ISOMoney<Currency.COP>

/// COU Money
public typealias COU = ISOMoney<Currency.COU>

/// CRC Money
public typealias CRC = ISOMoney<Currency.CRC>

/// CSD Money
public typealias CSD = ISOMoney<Currency.CSD>

/// CSK Money
public typealias CSK = ISOMoney<Currency.CSK>

/// CUC Money
public typealias CUC = ISOMoney<Currency.CUC>

/// CUP Money
public typealias CUP = ISOMoney<Currency.CUP>

/// CVE Money
public typealias CVE = ISOMoney<Currency.CVE>

/// CYP Money
public typealias CYP = ISOMoney<Currency.CYP>

/// CZK Money
public typealias CZK = ISOMoney<Currency.CZK>

/// DDM Money
public typealias DDM = ISOMoney<Currency.DDM>

/// DEM Money
public typealias DEM = ISOMoney<Currency.DEM>

/// DJF Money
public typealias DJF = ISOMoney<Currency.DJF>

/// DKK Money
public typealias DKK = ISOMoney<Currency.DKK>

/// DOP Money
public typealias DOP = ISOMoney<Currency.DOP>

/// DZD Money
public typealias DZD = ISOMoney<Currency.DZD>

/// ECS Money
public typealias ECS = ISOMoney<Currency.ECS>

/// ECV Money
public typealias ECV = ISOMoney<Currency.ECV>

/// EEK Money
public typealias EEK = ISOMoney<Currency.EEK>

/// EGP Money
public typealias EGP = ISOMoney<Currency.EGP>

/// EQE Money
public typealias EQE = ISOMoney<Currency.EQE>

/// ERN Money
public typealias ERN = ISOMoney<Currency.ERN>

/// ESA Money
public typealias ESA = ISOMoney<Currency.ESA>

/// ESB Money
public typealias ESB = ISOMoney<Currency.ESB>

/// ESP Money
public typealias ESP = ISOMoney<Currency.ESP>

/// ETB Money
public typealias ETB = ISOMoney<Currency.ETB>

/// EUR Money
public typealias EUR = ISOMoney<Currency.EUR>

/// FIM Money
public typealias FIM = ISOMoney<Currency.FIM>

/// FJD Money
public typealias FJD = ISOMoney<Currency.FJD>

/// FKP Money
public typealias FKP = ISOMoney<Currency.FKP>

/// FRF Money
public typealias FRF = ISOMoney<Currency.FRF>

/// GBP Money
public typealias GBP = ISOMoney<Currency.GBP>

/// GEK Money
public typealias GEK = ISOMoney<Currency.GEK>

/// GEL Money
public typealias GEL = ISOMoney<Currency.GEL>

/// GHC Money
public typealias GHC = ISOMoney<Currency.GHC>

/// GHS Money
public typealias GHS = ISOMoney<Currency.GHS>

/// GIP Money
public typealias GIP = ISOMoney<Currency.GIP>

/// GMD Money
public typealias GMD = ISOMoney<Currency.GMD>

/// GNF Money
public typealias GNF = ISOMoney<Currency.GNF>

/// GNS Money
public typealias GNS = ISOMoney<Currency.GNS>

/// GQE Money
public typealias GQE = ISOMoney<Currency.GQE>

/// GRD Money
public typealias GRD = ISOMoney<Currency.GRD>

/// GTQ Money
public typealias GTQ = ISOMoney<Currency.GTQ>

/// GWE Money
public typealias GWE = ISOMoney<Currency.GWE>

/// GWP Money
public typealias GWP = ISOMoney<Currency.GWP>

/// GYD Money
public typealias GYD = ISOMoney<Currency.GYD>

/// HKD Money
public typealias HKD = ISOMoney<Currency.HKD>

/// HNL Money
public typealias HNL = ISOMoney<Currency.HNL>

/// HRD Money
public typealias HRD = ISOMoney<Currency.HRD>

/// HRK Money
public typealias HRK = ISOMoney<Currency.HRK>

/// HTG Money
public typealias HTG = ISOMoney<Currency.HTG>

/// HUF Money
public typealias HUF = ISOMoney<Currency.HUF>

/// IDR Money
public typealias IDR = ISOMoney<Currency.IDR>

/// IEP Money
public typealias IEP = ISOMoney<Currency.IEP>

/// ILP Money
public typealias ILP = ISOMoney<Currency.ILP>

/// ILR Money
public typealias ILR = ISOMoney<Currency.ILR>

/// ILS Money
public typealias ILS = ISOMoney<Currency.ILS>

/// INR Money
public typealias INR = ISOMoney<Currency.INR>

/// IQD Money
public typealias IQD = ISOMoney<Currency.IQD>

/// IRR Money
public typealias IRR = ISOMoney<Currency.IRR>

/// ISJ Money
public typealias ISJ = ISOMoney<Currency.ISJ>

/// ISK Money
public typealias ISK = ISOMoney<Currency.ISK>

/// ITL Money
public typealias ITL = ISOMoney<Currency.ITL>

/// JMD Money
public typealias JMD = ISOMoney<Currency.JMD>

/// JOD Money
public typealias JOD = ISOMoney<Currency.JOD>

/// JPY Money
public typealias JPY = ISOMoney<Currency.JPY>

/// KES Money
public typealias KES = ISOMoney<Currency.KES>

/// KGS Money
public typealias KGS = ISOMoney<Currency.KGS>

/// KHR Money
public typealias KHR = ISOMoney<Currency.KHR>

/// KMF Money
public typealias KMF = ISOMoney<Currency.KMF>

/// KPW Money
public typealias KPW = ISOMoney<Currency.KPW>

/// KRH Money
public typealias KRH = ISOMoney<Currency.KRH>

/// KRO Money
public typealias KRO = ISOMoney<Currency.KRO>

/// KRW Money
public typealias KRW = ISOMoney<Currency.KRW>

/// KWD Money
public typealias KWD = ISOMoney<Currency.KWD>

/// KYD Money
public typealias KYD = ISOMoney<Currency.KYD>

/// KZT Money
public typealias KZT = ISOMoney<Currency.KZT>

/// LAK Money
public typealias LAK = ISOMoney<Currency.LAK>

/// LBP Money
public typealias LBP = ISOMoney<Currency.LBP>

/// LKR Money
public typealias LKR = ISOMoney<Currency.LKR>

/// LRD Money
public typealias LRD = ISOMoney<Currency.LRD>

/// LSL Money
public typealias LSL = ISOMoney<Currency.LSL>

/// LSM Money
public typealias LSM = ISOMoney<Currency.LSM>

/// LTL Money
public typealias LTL = ISOMoney<Currency.LTL>

/// LTT Money
public typealias LTT = ISOMoney<Currency.LTT>

/// LUC Money
public typealias LUC = ISOMoney<Currency.LUC>

/// LUF Money
public typealias LUF = ISOMoney<Currency.LUF>

/// LUL Money
public typealias LUL = ISOMoney<Currency.LUL>

/// LVL Money
public typealias LVL = ISOMoney<Currency.LVL>

/// LVR Money
public typealias LVR = ISOMoney<Currency.LVR>

/// LYD Money
public typealias LYD = ISOMoney<Currency.LYD>

/// MAD Money
public typealias MAD = ISOMoney<Currency.MAD>

/// MAF Money
public typealias MAF = ISOMoney<Currency.MAF>

/// MCF Money
public typealias MCF = ISOMoney<Currency.MCF>

/// MDC Money
public typealias MDC = ISOMoney<Currency.MDC>

/// MDL Money
public typealias MDL = ISOMoney<Currency.MDL>

/// MGA Money
public typealias MGA = ISOMoney<Currency.MGA>

/// MGF Money
public typealias MGF = ISOMoney<Currency.MGF>

/// MKD Money
public typealias MKD = ISOMoney<Currency.MKD>

/// MKN Money
public typealias MKN = ISOMoney<Currency.MKN>

/// MLF Money
public typealias MLF = ISOMoney<Currency.MLF>

/// MMK Money
public typealias MMK = ISOMoney<Currency.MMK>

/// MNT Money
public typealias MNT = ISOMoney<Currency.MNT>

/// MOP Money
public typealias MOP = ISOMoney<Currency.MOP>

/// MRO Money
public typealias MRO = ISOMoney<Currency.MRO>

/// MTL Money
public typealias MTL = ISOMoney<Currency.MTL>

/// MTP Money
public typealias MTP = ISOMoney<Currency.MTP>

/// MUR Money
public typealias MUR = ISOMoney<Currency.MUR>

/// MVP Money
public typealias MVP = ISOMoney<Currency.MVP>

/// MVR Money
public typealias MVR = ISOMoney<Currency.MVR>

/// MWK Money
public typealias MWK = ISOMoney<Currency.MWK>

/// MXN Money
public typealias MXN = ISOMoney<Currency.MXN>

/// MXP Money
public typealias MXP = ISOMoney<Currency.MXP>

/// MXV Money
public typealias MXV = ISOMoney<Currency.MXV>

/// MYR Money
public typealias MYR = ISOMoney<Currency.MYR>

/// MZE Money
public typealias MZE = ISOMoney<Currency.MZE>

/// MZM Money
public typealias MZM = ISOMoney<Currency.MZM>

/// MZN Money
public typealias MZN = ISOMoney<Currency.MZN>

/// NAD Money
public typealias NAD = ISOMoney<Currency.NAD>

/// NGN Money
public typealias NGN = ISOMoney<Currency.NGN>

/// NIC Money
public typealias NIC = ISOMoney<Currency.NIC>

/// NIO Money
public typealias NIO = ISOMoney<Currency.NIO>

/// NLG Money
public typealias NLG = ISOMoney<Currency.NLG>

/// NOK Money
public typealias NOK = ISOMoney<Currency.NOK>

/// NPR Money
public typealias NPR = ISOMoney<Currency.NPR>

/// NZD Money
public typealias NZD = ISOMoney<Currency.NZD>

/// OMR Money
public typealias OMR = ISOMoney<Currency.OMR>

/// PAB Money
public typealias PAB = ISOMoney<Currency.PAB>

/// PEI Money
public typealias PEI = ISOMoney<Currency.PEI>

/// PEN Money
public typealias PEN = ISOMoney<Currency.PEN>

/// PES Money
public typealias PES = ISOMoney<Currency.PES>

/// PGK Money
public typealias PGK = ISOMoney<Currency.PGK>

/// PHP Money
public typealias PHP = ISOMoney<Currency.PHP>

/// PKR Money
public typealias PKR = ISOMoney<Currency.PKR>

/// PLN Money
public typealias PLN = ISOMoney<Currency.PLN>

/// PLZ Money
public typealias PLZ = ISOMoney<Currency.PLZ>

/// PTE Money
public typealias PTE = ISOMoney<Currency.PTE>

/// PYG Money
public typealias PYG = ISOMoney<Currency.PYG>

/// QAR Money
public typealias QAR = ISOMoney<Currency.QAR>

/// RHD Money
public typealias RHD = ISOMoney<Currency.RHD>

/// ROL Money
public typealias ROL = ISOMoney<Currency.ROL>

/// RON Money
public typealias RON = ISOMoney<Currency.RON>

/// RSD Money
public typealias RSD = ISOMoney<Currency.RSD>

/// RUB Money
public typealias RUB = ISOMoney<Currency.RUB>

/// RUR Money
public typealias RUR = ISOMoney<Currency.RUR>

/// RWF Money
public typealias RWF = ISOMoney<Currency.RWF>

/// SAR Money
public typealias SAR = ISOMoney<Currency.SAR>

/// SBD Money
public typealias SBD = ISOMoney<Currency.SBD>

/// SCR Money
public typealias SCR = ISOMoney<Currency.SCR>

/// SDD Money
public typealias SDD = ISOMoney<Currency.SDD>

/// SDG Money
public typealias SDG = ISOMoney<Currency.SDG>

/// SDP Money
public typealias SDP = ISOMoney<Currency.SDP>

/// SEK Money
public typealias SEK = ISOMoney<Currency.SEK>

/// SGD Money
public typealias SGD = ISOMoney<Currency.SGD>

/// SHP Money
public typealias SHP = ISOMoney<Currency.SHP>

/// SIT Money
public typealias SIT = ISOMoney<Currency.SIT>

/// SKK Money
public typealias SKK = ISOMoney<Currency.SKK>

/// SLL Money
public typealias SLL = ISOMoney<Currency.SLL>

/// SOS Money
public typealias SOS = ISOMoney<Currency.SOS>

/// SRD Money
public typealias SRD = ISOMoney<Currency.SRD>

/// SRG Money
public typealias SRG = ISOMoney<Currency.SRG>

/// SSP Money
public typealias SSP = ISOMoney<Currency.SSP>

/// STD Money
public typealias STD = ISOMoney<Currency.STD>

/// SUR Money
public typealias SUR = ISOMoney<Currency.SUR>

/// SVC Money
public typealias SVC = ISOMoney<Currency.SVC>

/// SYP Money
public typealias SYP = ISOMoney<Currency.SYP>

/// SZL Money
public typealias SZL = ISOMoney<Currency.SZL>

/// THB Money
public typealias THB = ISOMoney<Currency.THB>

/// TJR Money
public typealias TJR = ISOMoney<Currency.TJR>

/// TJS Money
public typealias TJS = ISOMoney<Currency.TJS>

/// TMM Money
public typealias TMM = ISOMoney<Currency.TMM>

/// TMT Money
public typealias TMT = ISOMoney<Currency.TMT>

/// TND Money
public typealias TND = ISOMoney<Currency.TND>

/// TOP Money
public typealias TOP = ISOMoney<Currency.TOP>

/// TPE Money
public typealias TPE = ISOMoney<Currency.TPE>

/// TRL Money
public typealias TRL = ISOMoney<Currency.TRL>

/// TRY Money
public typealias TRY = ISOMoney<Currency.TRY>

/// TTD Money
public typealias TTD = ISOMoney<Currency.TTD>

/// TWD Money
public typealias TWD = ISOMoney<Currency.TWD>

/// TZS Money
public typealias TZS = ISOMoney<Currency.TZS>

/// UAH Money
public typealias UAH = ISOMoney<Currency.UAH>

/// UAK Money
public typealias UAK = ISOMoney<Currency.UAK>

/// UGS Money
public typealias UGS = ISOMoney<Currency.UGS>

/// UGX Money
public typealias UGX = ISOMoney<Currency.UGX>

/// USD Money
public typealias USD = ISOMoney<Currency.USD>

/// USN Money
public typealias USN = ISOMoney<Currency.USN>

/// USS Money
public typealias USS = ISOMoney<Currency.USS>

/// UYI Money
public typealias UYI = ISOMoney<Currency.UYI>

/// UYP Money
public typealias UYP = ISOMoney<Currency.UYP>

/// UYU Money
public typealias UYU = ISOMoney<Currency.UYU>

/// UZS Money
public typealias UZS = ISOMoney<Currency.UZS>

/// VEB Money
public typealias VEB = ISOMoney<Currency.VEB>

/// VEF Money
public typealias VEF = ISOMoney<Currency.VEF>

/// VND Money
public typealias VND = ISOMoney<Currency.VND>

/// VNN Money
public typealias VNN = ISOMoney<Currency.VNN>

/// VUV Money
public typealias VUV = ISOMoney<Currency.VUV>

/// WST Money
public typealias WST = ISOMoney<Currency.WST>

/// XAF Money
public typealias XAF = ISOMoney<Currency.XAF>

/// XAG Money
public typealias XAG = ISOMoney<Currency.XAG>

/// XAU Money
public typealias XAU = ISOMoney<Currency.XAU>

/// XBA Money
public typealias XBA = ISOMoney<Currency.XBA>

/// XBB Money
public typealias XBB = ISOMoney<Currency.XBB>

/// XBC Money
public typealias XBC = ISOMoney<Currency.XBC>

/// XBD Money
public typealias XBD = ISOMoney<Currency.XBD>

/// XCD Money
public typealias XCD = ISOMoney<Currency.XCD>

/// XDR Money
public typealias XDR = ISOMoney<Currency.XDR>

/// XEU Money
public typealias XEU = ISOMoney<Currency.XEU>

/// XFO Money
public typealias XFO = ISOMoney<Currency.XFO>

/// XFU Money
public typealias XFU = ISOMoney<Currency.XFU>

/// XOF Money
public typealias XOF = ISOMoney<Currency.XOF>

/// XPD Money
public typealias XPD = ISOMoney<Currency.XPD>

/// XPF Money
public typealias XPF = ISOMoney<Currency.XPF>

/// XPT Money
public typealias XPT = ISOMoney<Currency.XPT>

/// XRE Money
public typealias XRE = ISOMoney<Currency.XRE>

/// XSU Money
public typealias XSU = ISOMoney<Currency.XSU>

/// XTS Money
public typealias XTS = ISOMoney<Currency.XTS>

/// XUA Money
public typealias XUA = ISOMoney<Currency.XUA>

/// XXX Money
public typealias XXX = ISOMoney<Currency.XXX>

/// YDD Money
public typealias YDD = ISOMoney<Currency.YDD>

/// YER Money
public typealias YER = ISOMoney<Currency.YER>

/// YUD Money
public typealias YUD = ISOMoney<Currency.YUD>

/// YUM Money
public typealias YUM = ISOMoney<Currency.YUM>

/// YUN Money
public typealias YUN = ISOMoney<Currency.YUN>

/// YUR Money
public typealias YUR = ISOMoney<Currency.YUR>

/// ZAL Money
public typealias ZAL = ISOMoney<Currency.ZAL>

/// ZAR Money
public typealias ZAR = ISOMoney<Currency.ZAR>

/// ZMK Money
public typealias ZMK = ISOMoney<Currency.ZMK>

/// ZMW Money
public typealias ZMW = ISOMoney<Currency.ZMW>

/// ZRN Money
public typealias ZRN = ISOMoney<Currency.ZRN>

/// ZRZ Money
public typealias ZRZ = ISOMoney<Currency.ZRZ>

/// ZWL Money
public typealias ZWL = ISOMoney<Currency.ZWL>

/// ZWR Money
public typealias ZWR = ISOMoney<Currency.ZWR>

/// ZWD Money
public typealias ZWD = ISOMoney<Currency.ZWD>
