// 
// Money, https://github.com/danthorpe/Money
// Created by Dan Thorpe, @danthorpe
// 
// Autogenerated from build scripts, do not manually edit this file.

extension Currency {

    public final class ADP: BaseCurrency, CurrencyType {
        public static var sharedInstance = ADP(code: "ADP")
    }

    public final class AED: BaseCurrency, CurrencyType {
        public static var sharedInstance = AED(code: "AED")
    }

    public final class AFA: BaseCurrency, CurrencyType {
        public static var sharedInstance = AFA(code: "AFA")
    }

    public final class AFN: BaseCurrency, CurrencyType {
        public static var sharedInstance = AFN(code: "AFN")
    }

    public final class ALK: BaseCurrency, CurrencyType {
        public static var sharedInstance = ALK(code: "ALK")
    }

    public final class ALL: BaseCurrency, CurrencyType {
        public static var sharedInstance = ALL(code: "ALL")
    }

    public final class AMD: BaseCurrency, CurrencyType {
        public static var sharedInstance = AMD(code: "AMD")
    }

    public final class ANG: BaseCurrency, CurrencyType {
        public static var sharedInstance = ANG(code: "ANG")
    }

    public final class AOA: BaseCurrency, CurrencyType {
        public static var sharedInstance = AOA(code: "AOA")
    }

    public final class AOK: BaseCurrency, CurrencyType {
        public static var sharedInstance = AOK(code: "AOK")
    }

    public final class AON: BaseCurrency, CurrencyType {
        public static var sharedInstance = AON(code: "AON")
    }

    public final class AOR: BaseCurrency, CurrencyType {
        public static var sharedInstance = AOR(code: "AOR")
    }

    public final class ARA: BaseCurrency, CurrencyType {
        public static var sharedInstance = ARA(code: "ARA")
    }

    public final class ARL: BaseCurrency, CurrencyType {
        public static var sharedInstance = ARL(code: "ARL")
    }

    public final class ARM: BaseCurrency, CurrencyType {
        public static var sharedInstance = ARM(code: "ARM")
    }

    public final class ARP: BaseCurrency, CurrencyType {
        public static var sharedInstance = ARP(code: "ARP")
    }

    public final class ARS: BaseCurrency, CurrencyType {
        public static var sharedInstance = ARS(code: "ARS")
    }

    public final class ATS: BaseCurrency, CurrencyType {
        public static var sharedInstance = ATS(code: "ATS")
    }

    public final class AUD: BaseCurrency, CurrencyType {
        public static var sharedInstance = AUD(code: "AUD")
    }

    public final class AWG: BaseCurrency, CurrencyType {
        public static var sharedInstance = AWG(code: "AWG")
    }

    public final class AZM: BaseCurrency, CurrencyType {
        public static var sharedInstance = AZM(code: "AZM")
    }

    public final class AZN: BaseCurrency, CurrencyType {
        public static var sharedInstance = AZN(code: "AZN")
    }

    public final class BAD: BaseCurrency, CurrencyType {
        public static var sharedInstance = BAD(code: "BAD")
    }

    public final class BAM: BaseCurrency, CurrencyType {
        public static var sharedInstance = BAM(code: "BAM")
    }

    public final class BAN: BaseCurrency, CurrencyType {
        public static var sharedInstance = BAN(code: "BAN")
    }

    public final class BBD: BaseCurrency, CurrencyType {
        public static var sharedInstance = BBD(code: "BBD")
    }

    public final class BDT: BaseCurrency, CurrencyType {
        public static var sharedInstance = BDT(code: "BDT")
    }

    public final class BEC: BaseCurrency, CurrencyType {
        public static var sharedInstance = BEC(code: "BEC")
    }

    public final class BEF: BaseCurrency, CurrencyType {
        public static var sharedInstance = BEF(code: "BEF")
    }

    public final class BEL: BaseCurrency, CurrencyType {
        public static var sharedInstance = BEL(code: "BEL")
    }

    public final class BGL: BaseCurrency, CurrencyType {
        public static var sharedInstance = BGL(code: "BGL")
    }

    public final class BGM: BaseCurrency, CurrencyType {
        public static var sharedInstance = BGM(code: "BGM")
    }

    public final class BGN: BaseCurrency, CurrencyType {
        public static var sharedInstance = BGN(code: "BGN")
    }

    public final class BGO: BaseCurrency, CurrencyType {
        public static var sharedInstance = BGO(code: "BGO")
    }

    public final class BHD: BaseCurrency, CurrencyType {
        public static var sharedInstance = BHD(code: "BHD")
    }

    public final class BIF: BaseCurrency, CurrencyType {
        public static var sharedInstance = BIF(code: "BIF")
    }

    public final class BMD: BaseCurrency, CurrencyType {
        public static var sharedInstance = BMD(code: "BMD")
    }

    public final class BND: BaseCurrency, CurrencyType {
        public static var sharedInstance = BND(code: "BND")
    }

    public final class BOB: BaseCurrency, CurrencyType {
        public static var sharedInstance = BOB(code: "BOB")
    }

    public final class BOL: BaseCurrency, CurrencyType {
        public static var sharedInstance = BOL(code: "BOL")
    }

    public final class BOP: BaseCurrency, CurrencyType {
        public static var sharedInstance = BOP(code: "BOP")
    }

    public final class BOV: BaseCurrency, CurrencyType {
        public static var sharedInstance = BOV(code: "BOV")
    }

    public final class BRB: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRB(code: "BRB")
    }

    public final class BRC: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRC(code: "BRC")
    }

    public final class BRE: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRE(code: "BRE")
    }

    public final class BRL: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRL(code: "BRL")
    }

    public final class BRN: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRN(code: "BRN")
    }

    public final class BRR: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRR(code: "BRR")
    }

    public final class BRZ: BaseCurrency, CurrencyType {
        public static var sharedInstance = BRZ(code: "BRZ")
    }

    public final class BSD: BaseCurrency, CurrencyType {
        public static var sharedInstance = BSD(code: "BSD")
    }

    public final class BTN: BaseCurrency, CurrencyType {
        public static var sharedInstance = BTN(code: "BTN")
    }

    public final class BUK: BaseCurrency, CurrencyType {
        public static var sharedInstance = BUK(code: "BUK")
    }

    public final class BWP: BaseCurrency, CurrencyType {
        public static var sharedInstance = BWP(code: "BWP")
    }

    public final class BYB: BaseCurrency, CurrencyType {
        public static var sharedInstance = BYB(code: "BYB")
    }

    public final class BYR: BaseCurrency, CurrencyType {
        public static var sharedInstance = BYR(code: "BYR")
    }

    public final class BZD: BaseCurrency, CurrencyType {
        public static var sharedInstance = BZD(code: "BZD")
    }

    public final class CAD: BaseCurrency, CurrencyType {
        public static var sharedInstance = CAD(code: "CAD")
    }

    public final class CDF: BaseCurrency, CurrencyType {
        public static var sharedInstance = CDF(code: "CDF")
    }

    public final class CHE: BaseCurrency, CurrencyType {
        public static var sharedInstance = CHE(code: "CHE")
    }

    public final class CHF: BaseCurrency, CurrencyType {
        public static var sharedInstance = CHF(code: "CHF")
    }

    public final class CHW: BaseCurrency, CurrencyType {
        public static var sharedInstance = CHW(code: "CHW")
    }

    public final class CLE: BaseCurrency, CurrencyType {
        public static var sharedInstance = CLE(code: "CLE")
    }

    public final class CLF: BaseCurrency, CurrencyType {
        public static var sharedInstance = CLF(code: "CLF")
    }

    public final class CLP: BaseCurrency, CurrencyType {
        public static var sharedInstance = CLP(code: "CLP")
    }

    public final class CNX: BaseCurrency, CurrencyType {
        public static var sharedInstance = CNX(code: "CNX")
    }

    public final class CNY: BaseCurrency, CurrencyType {
        public static var sharedInstance = CNY(code: "CNY")
    }

    public final class COP: BaseCurrency, CurrencyType {
        public static var sharedInstance = COP(code: "COP")
    }

    public final class COU: BaseCurrency, CurrencyType {
        public static var sharedInstance = COU(code: "COU")
    }

    public final class CRC: BaseCurrency, CurrencyType {
        public static var sharedInstance = CRC(code: "CRC")
    }

    public final class CSD: BaseCurrency, CurrencyType {
        public static var sharedInstance = CSD(code: "CSD")
    }

    public final class CSK: BaseCurrency, CurrencyType {
        public static var sharedInstance = CSK(code: "CSK")
    }

    public final class CUC: BaseCurrency, CurrencyType {
        public static var sharedInstance = CUC(code: "CUC")
    }

    public final class CUP: BaseCurrency, CurrencyType {
        public static var sharedInstance = CUP(code: "CUP")
    }

    public final class CVE: BaseCurrency, CurrencyType {
        public static var sharedInstance = CVE(code: "CVE")
    }

    public final class CYP: BaseCurrency, CurrencyType {
        public static var sharedInstance = CYP(code: "CYP")
    }

    public final class CZK: BaseCurrency, CurrencyType {
        public static var sharedInstance = CZK(code: "CZK")
    }

    public final class DDM: BaseCurrency, CurrencyType {
        public static var sharedInstance = DDM(code: "DDM")
    }

    public final class DEM: BaseCurrency, CurrencyType {
        public static var sharedInstance = DEM(code: "DEM")
    }

    public final class DJF: BaseCurrency, CurrencyType {
        public static var sharedInstance = DJF(code: "DJF")
    }

    public final class DKK: BaseCurrency, CurrencyType {
        public static var sharedInstance = DKK(code: "DKK")
    }

    public final class DOP: BaseCurrency, CurrencyType {
        public static var sharedInstance = DOP(code: "DOP")
    }

    public final class DZD: BaseCurrency, CurrencyType {
        public static var sharedInstance = DZD(code: "DZD")
    }

    public final class ECS: BaseCurrency, CurrencyType {
        public static var sharedInstance = ECS(code: "ECS")
    }

    public final class ECV: BaseCurrency, CurrencyType {
        public static var sharedInstance = ECV(code: "ECV")
    }

    public final class EEK: BaseCurrency, CurrencyType {
        public static var sharedInstance = EEK(code: "EEK")
    }

    public final class EGP: BaseCurrency, CurrencyType {
        public static var sharedInstance = EGP(code: "EGP")
    }

    public final class EQE: BaseCurrency, CurrencyType {
        public static var sharedInstance = EQE(code: "EQE")
    }

    public final class ERN: BaseCurrency, CurrencyType {
        public static var sharedInstance = ERN(code: "ERN")
    }

    public final class ESA: BaseCurrency, CurrencyType {
        public static var sharedInstance = ESA(code: "ESA")
    }

    public final class ESB: BaseCurrency, CurrencyType {
        public static var sharedInstance = ESB(code: "ESB")
    }

    public final class ESP: BaseCurrency, CurrencyType {
        public static var sharedInstance = ESP(code: "ESP")
    }

    public final class ETB: BaseCurrency, CurrencyType {
        public static var sharedInstance = ETB(code: "ETB")
    }

    public final class EUR: BaseCurrency, CurrencyType {
        public static var sharedInstance = EUR(code: "EUR")
    }

    public final class FIM: BaseCurrency, CurrencyType {
        public static var sharedInstance = FIM(code: "FIM")
    }

    public final class FJD: BaseCurrency, CurrencyType {
        public static var sharedInstance = FJD(code: "FJD")
    }

    public final class FKP: BaseCurrency, CurrencyType {
        public static var sharedInstance = FKP(code: "FKP")
    }

    public final class FRF: BaseCurrency, CurrencyType {
        public static var sharedInstance = FRF(code: "FRF")
    }

    public final class GBP: BaseCurrency, CurrencyType {
        public static var sharedInstance = GBP(code: "GBP")
    }

    public final class GEK: BaseCurrency, CurrencyType {
        public static var sharedInstance = GEK(code: "GEK")
    }

    public final class GEL: BaseCurrency, CurrencyType {
        public static var sharedInstance = GEL(code: "GEL")
    }

    public final class GHC: BaseCurrency, CurrencyType {
        public static var sharedInstance = GHC(code: "GHC")
    }

    public final class GHS: BaseCurrency, CurrencyType {
        public static var sharedInstance = GHS(code: "GHS")
    }

    public final class GIP: BaseCurrency, CurrencyType {
        public static var sharedInstance = GIP(code: "GIP")
    }

    public final class GMD: BaseCurrency, CurrencyType {
        public static var sharedInstance = GMD(code: "GMD")
    }

    public final class GNF: BaseCurrency, CurrencyType {
        public static var sharedInstance = GNF(code: "GNF")
    }

    public final class GNS: BaseCurrency, CurrencyType {
        public static var sharedInstance = GNS(code: "GNS")
    }

    public final class GQE: BaseCurrency, CurrencyType {
        public static var sharedInstance = GQE(code: "GQE")
    }

    public final class GRD: BaseCurrency, CurrencyType {
        public static var sharedInstance = GRD(code: "GRD")
    }

    public final class GTQ: BaseCurrency, CurrencyType {
        public static var sharedInstance = GTQ(code: "GTQ")
    }

    public final class GWE: BaseCurrency, CurrencyType {
        public static var sharedInstance = GWE(code: "GWE")
    }

    public final class GWP: BaseCurrency, CurrencyType {
        public static var sharedInstance = GWP(code: "GWP")
    }

    public final class GYD: BaseCurrency, CurrencyType {
        public static var sharedInstance = GYD(code: "GYD")
    }

    public final class HKD: BaseCurrency, CurrencyType {
        public static var sharedInstance = HKD(code: "HKD")
    }

    public final class HNL: BaseCurrency, CurrencyType {
        public static var sharedInstance = HNL(code: "HNL")
    }

    public final class HRD: BaseCurrency, CurrencyType {
        public static var sharedInstance = HRD(code: "HRD")
    }

    public final class HRK: BaseCurrency, CurrencyType {
        public static var sharedInstance = HRK(code: "HRK")
    }

    public final class HTG: BaseCurrency, CurrencyType {
        public static var sharedInstance = HTG(code: "HTG")
    }

    public final class HUF: BaseCurrency, CurrencyType {
        public static var sharedInstance = HUF(code: "HUF")
    }

    public final class IDR: BaseCurrency, CurrencyType {
        public static var sharedInstance = IDR(code: "IDR")
    }

    public final class IEP: BaseCurrency, CurrencyType {
        public static var sharedInstance = IEP(code: "IEP")
    }

    public final class ILP: BaseCurrency, CurrencyType {
        public static var sharedInstance = ILP(code: "ILP")
    }

    public final class ILR: BaseCurrency, CurrencyType {
        public static var sharedInstance = ILR(code: "ILR")
    }

    public final class ILS: BaseCurrency, CurrencyType {
        public static var sharedInstance = ILS(code: "ILS")
    }

    public final class INR: BaseCurrency, CurrencyType {
        public static var sharedInstance = INR(code: "INR")
    }

    public final class IQD: BaseCurrency, CurrencyType {
        public static var sharedInstance = IQD(code: "IQD")
    }

    public final class IRR: BaseCurrency, CurrencyType {
        public static var sharedInstance = IRR(code: "IRR")
    }

    public final class ISJ: BaseCurrency, CurrencyType {
        public static var sharedInstance = ISJ(code: "ISJ")
    }

    public final class ISK: BaseCurrency, CurrencyType {
        public static var sharedInstance = ISK(code: "ISK")
    }

    public final class ITL: BaseCurrency, CurrencyType {
        public static var sharedInstance = ITL(code: "ITL")
    }

    public final class JMD: BaseCurrency, CurrencyType {
        public static var sharedInstance = JMD(code: "JMD")
    }

    public final class JOD: BaseCurrency, CurrencyType {
        public static var sharedInstance = JOD(code: "JOD")
    }

    public final class JPY: BaseCurrency, CurrencyType {
        public static var sharedInstance = JPY(code: "JPY")
    }

    public final class KES: BaseCurrency, CurrencyType {
        public static var sharedInstance = KES(code: "KES")
    }

    public final class KGS: BaseCurrency, CurrencyType {
        public static var sharedInstance = KGS(code: "KGS")
    }

    public final class KHR: BaseCurrency, CurrencyType {
        public static var sharedInstance = KHR(code: "KHR")
    }

    public final class KMF: BaseCurrency, CurrencyType {
        public static var sharedInstance = KMF(code: "KMF")
    }

    public final class KPW: BaseCurrency, CurrencyType {
        public static var sharedInstance = KPW(code: "KPW")
    }

    public final class KRH: BaseCurrency, CurrencyType {
        public static var sharedInstance = KRH(code: "KRH")
    }

    public final class KRO: BaseCurrency, CurrencyType {
        public static var sharedInstance = KRO(code: "KRO")
    }

    public final class KRW: BaseCurrency, CurrencyType {
        public static var sharedInstance = KRW(code: "KRW")
    }

    public final class KWD: BaseCurrency, CurrencyType {
        public static var sharedInstance = KWD(code: "KWD")
    }

    public final class KYD: BaseCurrency, CurrencyType {
        public static var sharedInstance = KYD(code: "KYD")
    }

    public final class KZT: BaseCurrency, CurrencyType {
        public static var sharedInstance = KZT(code: "KZT")
    }

    public final class LAK: BaseCurrency, CurrencyType {
        public static var sharedInstance = LAK(code: "LAK")
    }

    public final class LBP: BaseCurrency, CurrencyType {
        public static var sharedInstance = LBP(code: "LBP")
    }

    public final class LKR: BaseCurrency, CurrencyType {
        public static var sharedInstance = LKR(code: "LKR")
    }

    public final class LRD: BaseCurrency, CurrencyType {
        public static var sharedInstance = LRD(code: "LRD")
    }

    public final class LSL: BaseCurrency, CurrencyType {
        public static var sharedInstance = LSL(code: "LSL")
    }

    public final class LSM: BaseCurrency, CurrencyType {
        public static var sharedInstance = LSM(code: "LSM")
    }

    public final class LTL: BaseCurrency, CurrencyType {
        public static var sharedInstance = LTL(code: "LTL")
    }

    public final class LTT: BaseCurrency, CurrencyType {
        public static var sharedInstance = LTT(code: "LTT")
    }

    public final class LUC: BaseCurrency, CurrencyType {
        public static var sharedInstance = LUC(code: "LUC")
    }

    public final class LUF: BaseCurrency, CurrencyType {
        public static var sharedInstance = LUF(code: "LUF")
    }

    public final class LUL: BaseCurrency, CurrencyType {
        public static var sharedInstance = LUL(code: "LUL")
    }

    public final class LVL: BaseCurrency, CurrencyType {
        public static var sharedInstance = LVL(code: "LVL")
    }

    public final class LVR: BaseCurrency, CurrencyType {
        public static var sharedInstance = LVR(code: "LVR")
    }

    public final class LYD: BaseCurrency, CurrencyType {
        public static var sharedInstance = LYD(code: "LYD")
    }

    public final class MAD: BaseCurrency, CurrencyType {
        public static var sharedInstance = MAD(code: "MAD")
    }

    public final class MAF: BaseCurrency, CurrencyType {
        public static var sharedInstance = MAF(code: "MAF")
    }

    public final class MCF: BaseCurrency, CurrencyType {
        public static var sharedInstance = MCF(code: "MCF")
    }

    public final class MDC: BaseCurrency, CurrencyType {
        public static var sharedInstance = MDC(code: "MDC")
    }

    public final class MDL: BaseCurrency, CurrencyType {
        public static var sharedInstance = MDL(code: "MDL")
    }

    public final class MGA: BaseCurrency, CurrencyType {
        public static var sharedInstance = MGA(code: "MGA")
    }

    public final class MGF: BaseCurrency, CurrencyType {
        public static var sharedInstance = MGF(code: "MGF")
    }

    public final class MKD: BaseCurrency, CurrencyType {
        public static var sharedInstance = MKD(code: "MKD")
    }

    public final class MKN: BaseCurrency, CurrencyType {
        public static var sharedInstance = MKN(code: "MKN")
    }

    public final class MLF: BaseCurrency, CurrencyType {
        public static var sharedInstance = MLF(code: "MLF")
    }

    public final class MMK: BaseCurrency, CurrencyType {
        public static var sharedInstance = MMK(code: "MMK")
    }

    public final class MNT: BaseCurrency, CurrencyType {
        public static var sharedInstance = MNT(code: "MNT")
    }

    public final class MOP: BaseCurrency, CurrencyType {
        public static var sharedInstance = MOP(code: "MOP")
    }

    public final class MRO: BaseCurrency, CurrencyType {
        public static var sharedInstance = MRO(code: "MRO")
    }

    public final class MTL: BaseCurrency, CurrencyType {
        public static var sharedInstance = MTL(code: "MTL")
    }

    public final class MTP: BaseCurrency, CurrencyType {
        public static var sharedInstance = MTP(code: "MTP")
    }

    public final class MUR: BaseCurrency, CurrencyType {
        public static var sharedInstance = MUR(code: "MUR")
    }

    public final class MVP: BaseCurrency, CurrencyType {
        public static var sharedInstance = MVP(code: "MVP")
    }

    public final class MVR: BaseCurrency, CurrencyType {
        public static var sharedInstance = MVR(code: "MVR")
    }

    public final class MWK: BaseCurrency, CurrencyType {
        public static var sharedInstance = MWK(code: "MWK")
    }

    public final class MXN: BaseCurrency, CurrencyType {
        public static var sharedInstance = MXN(code: "MXN")
    }

    public final class MXP: BaseCurrency, CurrencyType {
        public static var sharedInstance = MXP(code: "MXP")
    }

    public final class MXV: BaseCurrency, CurrencyType {
        public static var sharedInstance = MXV(code: "MXV")
    }

    public final class MYR: BaseCurrency, CurrencyType {
        public static var sharedInstance = MYR(code: "MYR")
    }

    public final class MZE: BaseCurrency, CurrencyType {
        public static var sharedInstance = MZE(code: "MZE")
    }

    public final class MZM: BaseCurrency, CurrencyType {
        public static var sharedInstance = MZM(code: "MZM")
    }

    public final class MZN: BaseCurrency, CurrencyType {
        public static var sharedInstance = MZN(code: "MZN")
    }

    public final class NAD: BaseCurrency, CurrencyType {
        public static var sharedInstance = NAD(code: "NAD")
    }

    public final class NGN: BaseCurrency, CurrencyType {
        public static var sharedInstance = NGN(code: "NGN")
    }

    public final class NIC: BaseCurrency, CurrencyType {
        public static var sharedInstance = NIC(code: "NIC")
    }

    public final class NIO: BaseCurrency, CurrencyType {
        public static var sharedInstance = NIO(code: "NIO")
    }

    public final class NLG: BaseCurrency, CurrencyType {
        public static var sharedInstance = NLG(code: "NLG")
    }

    public final class NOK: BaseCurrency, CurrencyType {
        public static var sharedInstance = NOK(code: "NOK")
    }

    public final class NPR: BaseCurrency, CurrencyType {
        public static var sharedInstance = NPR(code: "NPR")
    }

    public final class NZD: BaseCurrency, CurrencyType {
        public static var sharedInstance = NZD(code: "NZD")
    }

    public final class OMR: BaseCurrency, CurrencyType {
        public static var sharedInstance = OMR(code: "OMR")
    }

    public final class PAB: BaseCurrency, CurrencyType {
        public static var sharedInstance = PAB(code: "PAB")
    }

    public final class PEI: BaseCurrency, CurrencyType {
        public static var sharedInstance = PEI(code: "PEI")
    }

    public final class PEN: BaseCurrency, CurrencyType {
        public static var sharedInstance = PEN(code: "PEN")
    }

    public final class PES: BaseCurrency, CurrencyType {
        public static var sharedInstance = PES(code: "PES")
    }

    public final class PGK: BaseCurrency, CurrencyType {
        public static var sharedInstance = PGK(code: "PGK")
    }

    public final class PHP: BaseCurrency, CurrencyType {
        public static var sharedInstance = PHP(code: "PHP")
    }

    public final class PKR: BaseCurrency, CurrencyType {
        public static var sharedInstance = PKR(code: "PKR")
    }

    public final class PLN: BaseCurrency, CurrencyType {
        public static var sharedInstance = PLN(code: "PLN")
    }

    public final class PLZ: BaseCurrency, CurrencyType {
        public static var sharedInstance = PLZ(code: "PLZ")
    }

    public final class PTE: BaseCurrency, CurrencyType {
        public static var sharedInstance = PTE(code: "PTE")
    }

    public final class PYG: BaseCurrency, CurrencyType {
        public static var sharedInstance = PYG(code: "PYG")
    }

    public final class QAR: BaseCurrency, CurrencyType {
        public static var sharedInstance = QAR(code: "QAR")
    }

    public final class RHD: BaseCurrency, CurrencyType {
        public static var sharedInstance = RHD(code: "RHD")
    }

    public final class ROL: BaseCurrency, CurrencyType {
        public static var sharedInstance = ROL(code: "ROL")
    }

    public final class RON: BaseCurrency, CurrencyType {
        public static var sharedInstance = RON(code: "RON")
    }

    public final class RSD: BaseCurrency, CurrencyType {
        public static var sharedInstance = RSD(code: "RSD")
    }

    public final class RUB: BaseCurrency, CurrencyType {
        public static var sharedInstance = RUB(code: "RUB")
    }

    public final class RUR: BaseCurrency, CurrencyType {
        public static var sharedInstance = RUR(code: "RUR")
    }

    public final class RWF: BaseCurrency, CurrencyType {
        public static var sharedInstance = RWF(code: "RWF")
    }

    public final class SAR: BaseCurrency, CurrencyType {
        public static var sharedInstance = SAR(code: "SAR")
    }

    public final class SBD: BaseCurrency, CurrencyType {
        public static var sharedInstance = SBD(code: "SBD")
    }

    public final class SCR: BaseCurrency, CurrencyType {
        public static var sharedInstance = SCR(code: "SCR")
    }

    public final class SDD: BaseCurrency, CurrencyType {
        public static var sharedInstance = SDD(code: "SDD")
    }

    public final class SDG: BaseCurrency, CurrencyType {
        public static var sharedInstance = SDG(code: "SDG")
    }

    public final class SDP: BaseCurrency, CurrencyType {
        public static var sharedInstance = SDP(code: "SDP")
    }

    public final class SEK: BaseCurrency, CurrencyType {
        public static var sharedInstance = SEK(code: "SEK")
    }

    public final class SGD: BaseCurrency, CurrencyType {
        public static var sharedInstance = SGD(code: "SGD")
    }

    public final class SHP: BaseCurrency, CurrencyType {
        public static var sharedInstance = SHP(code: "SHP")
    }

    public final class SIT: BaseCurrency, CurrencyType {
        public static var sharedInstance = SIT(code: "SIT")
    }

    public final class SKK: BaseCurrency, CurrencyType {
        public static var sharedInstance = SKK(code: "SKK")
    }

    public final class SLL: BaseCurrency, CurrencyType {
        public static var sharedInstance = SLL(code: "SLL")
    }

    public final class SOS: BaseCurrency, CurrencyType {
        public static var sharedInstance = SOS(code: "SOS")
    }

    public final class SRD: BaseCurrency, CurrencyType {
        public static var sharedInstance = SRD(code: "SRD")
    }

    public final class SRG: BaseCurrency, CurrencyType {
        public static var sharedInstance = SRG(code: "SRG")
    }

    public final class SSP: BaseCurrency, CurrencyType {
        public static var sharedInstance = SSP(code: "SSP")
    }

    public final class STD: BaseCurrency, CurrencyType {
        public static var sharedInstance = STD(code: "STD")
    }

    public final class SUR: BaseCurrency, CurrencyType {
        public static var sharedInstance = SUR(code: "SUR")
    }

    public final class SVC: BaseCurrency, CurrencyType {
        public static var sharedInstance = SVC(code: "SVC")
    }

    public final class SYP: BaseCurrency, CurrencyType {
        public static var sharedInstance = SYP(code: "SYP")
    }

    public final class SZL: BaseCurrency, CurrencyType {
        public static var sharedInstance = SZL(code: "SZL")
    }

    public final class THB: BaseCurrency, CurrencyType {
        public static var sharedInstance = THB(code: "THB")
    }

    public final class TJR: BaseCurrency, CurrencyType {
        public static var sharedInstance = TJR(code: "TJR")
    }

    public final class TJS: BaseCurrency, CurrencyType {
        public static var sharedInstance = TJS(code: "TJS")
    }

    public final class TMM: BaseCurrency, CurrencyType {
        public static var sharedInstance = TMM(code: "TMM")
    }

    public final class TMT: BaseCurrency, CurrencyType {
        public static var sharedInstance = TMT(code: "TMT")
    }

    public final class TND: BaseCurrency, CurrencyType {
        public static var sharedInstance = TND(code: "TND")
    }

    public final class TOP: BaseCurrency, CurrencyType {
        public static var sharedInstance = TOP(code: "TOP")
    }

    public final class TPE: BaseCurrency, CurrencyType {
        public static var sharedInstance = TPE(code: "TPE")
    }

    public final class TRL: BaseCurrency, CurrencyType {
        public static var sharedInstance = TRL(code: "TRL")
    }

    public final class TRY: BaseCurrency, CurrencyType {
        public static var sharedInstance = TRY(code: "TRY")
    }

    public final class TTD: BaseCurrency, CurrencyType {
        public static var sharedInstance = TTD(code: "TTD")
    }

    public final class TWD: BaseCurrency, CurrencyType {
        public static var sharedInstance = TWD(code: "TWD")
    }

    public final class TZS: BaseCurrency, CurrencyType {
        public static var sharedInstance = TZS(code: "TZS")
    }

    public final class UAH: BaseCurrency, CurrencyType {
        public static var sharedInstance = UAH(code: "UAH")
    }

    public final class UAK: BaseCurrency, CurrencyType {
        public static var sharedInstance = UAK(code: "UAK")
    }

    public final class UGS: BaseCurrency, CurrencyType {
        public static var sharedInstance = UGS(code: "UGS")
    }

    public final class UGX: BaseCurrency, CurrencyType {
        public static var sharedInstance = UGX(code: "UGX")
    }

    public final class USD: BaseCurrency, CurrencyType {
        public static var sharedInstance = USD(code: "USD")
    }

    public final class USN: BaseCurrency, CurrencyType {
        public static var sharedInstance = USN(code: "USN")
    }

    public final class USS: BaseCurrency, CurrencyType {
        public static var sharedInstance = USS(code: "USS")
    }

    public final class UYI: BaseCurrency, CurrencyType {
        public static var sharedInstance = UYI(code: "UYI")
    }

    public final class UYP: BaseCurrency, CurrencyType {
        public static var sharedInstance = UYP(code: "UYP")
    }

    public final class UYU: BaseCurrency, CurrencyType {
        public static var sharedInstance = UYU(code: "UYU")
    }

    public final class UZS: BaseCurrency, CurrencyType {
        public static var sharedInstance = UZS(code: "UZS")
    }

    public final class VEB: BaseCurrency, CurrencyType {
        public static var sharedInstance = VEB(code: "VEB")
    }

    public final class VEF: BaseCurrency, CurrencyType {
        public static var sharedInstance = VEF(code: "VEF")
    }

    public final class VND: BaseCurrency, CurrencyType {
        public static var sharedInstance = VND(code: "VND")
    }

    public final class VNN: BaseCurrency, CurrencyType {
        public static var sharedInstance = VNN(code: "VNN")
    }

    public final class VUV: BaseCurrency, CurrencyType {
        public static var sharedInstance = VUV(code: "VUV")
    }

    public final class WST: BaseCurrency, CurrencyType {
        public static var sharedInstance = WST(code: "WST")
    }

    public final class XAF: BaseCurrency, CurrencyType {
        public static var sharedInstance = XAF(code: "XAF")
    }

    public final class XAG: BaseCurrency, CurrencyType {
        public static var sharedInstance = XAG(code: "XAG")
    }

    public final class XAU: BaseCurrency, CurrencyType {
        public static var sharedInstance = XAU(code: "XAU")
    }

    public final class XBA: BaseCurrency, CurrencyType {
        public static var sharedInstance = XBA(code: "XBA")
    }

    public final class XBB: BaseCurrency, CurrencyType {
        public static var sharedInstance = XBB(code: "XBB")
    }

    public final class XBC: BaseCurrency, CurrencyType {
        public static var sharedInstance = XBC(code: "XBC")
    }

    public final class XBD: BaseCurrency, CurrencyType {
        public static var sharedInstance = XBD(code: "XBD")
    }

    public final class XCD: BaseCurrency, CurrencyType {
        public static var sharedInstance = XCD(code: "XCD")
    }

    public final class XDR: BaseCurrency, CurrencyType {
        public static var sharedInstance = XDR(code: "XDR")
    }

    public final class XEU: BaseCurrency, CurrencyType {
        public static var sharedInstance = XEU(code: "XEU")
    }

    public final class XFO: BaseCurrency, CurrencyType {
        public static var sharedInstance = XFO(code: "XFO")
    }

    public final class XFU: BaseCurrency, CurrencyType {
        public static var sharedInstance = XFU(code: "XFU")
    }

    public final class XOF: BaseCurrency, CurrencyType {
        public static var sharedInstance = XOF(code: "XOF")
    }

    public final class XPD: BaseCurrency, CurrencyType {
        public static var sharedInstance = XPD(code: "XPD")
    }

    public final class XPF: BaseCurrency, CurrencyType {
        public static var sharedInstance = XPF(code: "XPF")
    }

    public final class XPT: BaseCurrency, CurrencyType {
        public static var sharedInstance = XPT(code: "XPT")
    }

    public final class XRE: BaseCurrency, CurrencyType {
        public static var sharedInstance = XRE(code: "XRE")
    }

    public final class XSU: BaseCurrency, CurrencyType {
        public static var sharedInstance = XSU(code: "XSU")
    }

    public final class XTS: BaseCurrency, CurrencyType {
        public static var sharedInstance = XTS(code: "XTS")
    }

    public final class XUA: BaseCurrency, CurrencyType {
        public static var sharedInstance = XUA(code: "XUA")
    }

    public final class XXX: BaseCurrency, CurrencyType {
        public static var sharedInstance = XXX(code: "XXX")
    }

    public final class YDD: BaseCurrency, CurrencyType {
        public static var sharedInstance = YDD(code: "YDD")
    }

    public final class YER: BaseCurrency, CurrencyType {
        public static var sharedInstance = YER(code: "YER")
    }

    public final class YUD: BaseCurrency, CurrencyType {
        public static var sharedInstance = YUD(code: "YUD")
    }

    public final class YUM: BaseCurrency, CurrencyType {
        public static var sharedInstance = YUM(code: "YUM")
    }

    public final class YUN: BaseCurrency, CurrencyType {
        public static var sharedInstance = YUN(code: "YUN")
    }

    public final class YUR: BaseCurrency, CurrencyType {
        public static var sharedInstance = YUR(code: "YUR")
    }

    public final class ZAL: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZAL(code: "ZAL")
    }

    public final class ZAR: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZAR(code: "ZAR")
    }

    public final class ZMK: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZMK(code: "ZMK")
    }

    public final class ZMW: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZMW(code: "ZMW")
    }

    public final class ZRN: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZRN(code: "ZRN")
    }

    public final class ZRZ: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZRZ(code: "ZRZ")
    }

    public final class ZWL: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZWL(code: "ZWL")
    }

    public final class ZWR: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZWR(code: "ZWR")
    }

    public final class ZWD: BaseCurrency, CurrencyType {
        public static var sharedInstance = ZWD(code: "ZWD")
    }
}


public typealias ADP = _Money<Currency.ADP>
public typealias AED = _Money<Currency.AED>
public typealias AFA = _Money<Currency.AFA>
public typealias AFN = _Money<Currency.AFN>
public typealias ALK = _Money<Currency.ALK>
public typealias ALL = _Money<Currency.ALL>
public typealias AMD = _Money<Currency.AMD>
public typealias ANG = _Money<Currency.ANG>
public typealias AOA = _Money<Currency.AOA>
public typealias AOK = _Money<Currency.AOK>
public typealias AON = _Money<Currency.AON>
public typealias AOR = _Money<Currency.AOR>
public typealias ARA = _Money<Currency.ARA>
public typealias ARL = _Money<Currency.ARL>
public typealias ARM = _Money<Currency.ARM>
public typealias ARP = _Money<Currency.ARP>
public typealias ARS = _Money<Currency.ARS>
public typealias ATS = _Money<Currency.ATS>
public typealias AUD = _Money<Currency.AUD>
public typealias AWG = _Money<Currency.AWG>
public typealias AZM = _Money<Currency.AZM>
public typealias AZN = _Money<Currency.AZN>
public typealias BAD = _Money<Currency.BAD>
public typealias BAM = _Money<Currency.BAM>
public typealias BAN = _Money<Currency.BAN>
public typealias BBD = _Money<Currency.BBD>
public typealias BDT = _Money<Currency.BDT>
public typealias BEC = _Money<Currency.BEC>
public typealias BEF = _Money<Currency.BEF>
public typealias BEL = _Money<Currency.BEL>
public typealias BGL = _Money<Currency.BGL>
public typealias BGM = _Money<Currency.BGM>
public typealias BGN = _Money<Currency.BGN>
public typealias BGO = _Money<Currency.BGO>
public typealias BHD = _Money<Currency.BHD>
public typealias BIF = _Money<Currency.BIF>
public typealias BMD = _Money<Currency.BMD>
public typealias BND = _Money<Currency.BND>
public typealias BOB = _Money<Currency.BOB>
public typealias BOL = _Money<Currency.BOL>
public typealias BOP = _Money<Currency.BOP>
public typealias BOV = _Money<Currency.BOV>
public typealias BRB = _Money<Currency.BRB>
public typealias BRC = _Money<Currency.BRC>
public typealias BRE = _Money<Currency.BRE>
public typealias BRL = _Money<Currency.BRL>
public typealias BRN = _Money<Currency.BRN>
public typealias BRR = _Money<Currency.BRR>
public typealias BRZ = _Money<Currency.BRZ>
public typealias BSD = _Money<Currency.BSD>
public typealias BTN = _Money<Currency.BTN>
public typealias BUK = _Money<Currency.BUK>
public typealias BWP = _Money<Currency.BWP>
public typealias BYB = _Money<Currency.BYB>
public typealias BYR = _Money<Currency.BYR>
public typealias BZD = _Money<Currency.BZD>
public typealias CAD = _Money<Currency.CAD>
public typealias CDF = _Money<Currency.CDF>
public typealias CHE = _Money<Currency.CHE>
public typealias CHF = _Money<Currency.CHF>
public typealias CHW = _Money<Currency.CHW>
public typealias CLE = _Money<Currency.CLE>
public typealias CLF = _Money<Currency.CLF>
public typealias CLP = _Money<Currency.CLP>
public typealias CNX = _Money<Currency.CNX>
public typealias CNY = _Money<Currency.CNY>
public typealias COP = _Money<Currency.COP>
public typealias COU = _Money<Currency.COU>
public typealias CRC = _Money<Currency.CRC>
public typealias CSD = _Money<Currency.CSD>
public typealias CSK = _Money<Currency.CSK>
public typealias CUC = _Money<Currency.CUC>
public typealias CUP = _Money<Currency.CUP>
public typealias CVE = _Money<Currency.CVE>
public typealias CYP = _Money<Currency.CYP>
public typealias CZK = _Money<Currency.CZK>
public typealias DDM = _Money<Currency.DDM>
public typealias DEM = _Money<Currency.DEM>
public typealias DJF = _Money<Currency.DJF>
public typealias DKK = _Money<Currency.DKK>
public typealias DOP = _Money<Currency.DOP>
public typealias DZD = _Money<Currency.DZD>
public typealias ECS = _Money<Currency.ECS>
public typealias ECV = _Money<Currency.ECV>
public typealias EEK = _Money<Currency.EEK>
public typealias EGP = _Money<Currency.EGP>
public typealias EQE = _Money<Currency.EQE>
public typealias ERN = _Money<Currency.ERN>
public typealias ESA = _Money<Currency.ESA>
public typealias ESB = _Money<Currency.ESB>
public typealias ESP = _Money<Currency.ESP>
public typealias ETB = _Money<Currency.ETB>
public typealias EUR = _Money<Currency.EUR>
public typealias FIM = _Money<Currency.FIM>
public typealias FJD = _Money<Currency.FJD>
public typealias FKP = _Money<Currency.FKP>
public typealias FRF = _Money<Currency.FRF>
public typealias GBP = _Money<Currency.GBP>
public typealias GEK = _Money<Currency.GEK>
public typealias GEL = _Money<Currency.GEL>
public typealias GHC = _Money<Currency.GHC>
public typealias GHS = _Money<Currency.GHS>
public typealias GIP = _Money<Currency.GIP>
public typealias GMD = _Money<Currency.GMD>
public typealias GNF = _Money<Currency.GNF>
public typealias GNS = _Money<Currency.GNS>
public typealias GQE = _Money<Currency.GQE>
public typealias GRD = _Money<Currency.GRD>
public typealias GTQ = _Money<Currency.GTQ>
public typealias GWE = _Money<Currency.GWE>
public typealias GWP = _Money<Currency.GWP>
public typealias GYD = _Money<Currency.GYD>
public typealias HKD = _Money<Currency.HKD>
public typealias HNL = _Money<Currency.HNL>
public typealias HRD = _Money<Currency.HRD>
public typealias HRK = _Money<Currency.HRK>
public typealias HTG = _Money<Currency.HTG>
public typealias HUF = _Money<Currency.HUF>
public typealias IDR = _Money<Currency.IDR>
public typealias IEP = _Money<Currency.IEP>
public typealias ILP = _Money<Currency.ILP>
public typealias ILR = _Money<Currency.ILR>
public typealias ILS = _Money<Currency.ILS>
public typealias INR = _Money<Currency.INR>
public typealias IQD = _Money<Currency.IQD>
public typealias IRR = _Money<Currency.IRR>
public typealias ISJ = _Money<Currency.ISJ>
public typealias ISK = _Money<Currency.ISK>
public typealias ITL = _Money<Currency.ITL>
public typealias JMD = _Money<Currency.JMD>
public typealias JOD = _Money<Currency.JOD>
public typealias JPY = _Money<Currency.JPY>
public typealias KES = _Money<Currency.KES>
public typealias KGS = _Money<Currency.KGS>
public typealias KHR = _Money<Currency.KHR>
public typealias KMF = _Money<Currency.KMF>
public typealias KPW = _Money<Currency.KPW>
public typealias KRH = _Money<Currency.KRH>
public typealias KRO = _Money<Currency.KRO>
public typealias KRW = _Money<Currency.KRW>
public typealias KWD = _Money<Currency.KWD>
public typealias KYD = _Money<Currency.KYD>
public typealias KZT = _Money<Currency.KZT>
public typealias LAK = _Money<Currency.LAK>
public typealias LBP = _Money<Currency.LBP>
public typealias LKR = _Money<Currency.LKR>
public typealias LRD = _Money<Currency.LRD>
public typealias LSL = _Money<Currency.LSL>
public typealias LSM = _Money<Currency.LSM>
public typealias LTL = _Money<Currency.LTL>
public typealias LTT = _Money<Currency.LTT>
public typealias LUC = _Money<Currency.LUC>
public typealias LUF = _Money<Currency.LUF>
public typealias LUL = _Money<Currency.LUL>
public typealias LVL = _Money<Currency.LVL>
public typealias LVR = _Money<Currency.LVR>
public typealias LYD = _Money<Currency.LYD>
public typealias MAD = _Money<Currency.MAD>
public typealias MAF = _Money<Currency.MAF>
public typealias MCF = _Money<Currency.MCF>
public typealias MDC = _Money<Currency.MDC>
public typealias MDL = _Money<Currency.MDL>
public typealias MGA = _Money<Currency.MGA>
public typealias MGF = _Money<Currency.MGF>
public typealias MKD = _Money<Currency.MKD>
public typealias MKN = _Money<Currency.MKN>
public typealias MLF = _Money<Currency.MLF>
public typealias MMK = _Money<Currency.MMK>
public typealias MNT = _Money<Currency.MNT>
public typealias MOP = _Money<Currency.MOP>
public typealias MRO = _Money<Currency.MRO>
public typealias MTL = _Money<Currency.MTL>
public typealias MTP = _Money<Currency.MTP>
public typealias MUR = _Money<Currency.MUR>
public typealias MVP = _Money<Currency.MVP>
public typealias MVR = _Money<Currency.MVR>
public typealias MWK = _Money<Currency.MWK>
public typealias MXN = _Money<Currency.MXN>
public typealias MXP = _Money<Currency.MXP>
public typealias MXV = _Money<Currency.MXV>
public typealias MYR = _Money<Currency.MYR>
public typealias MZE = _Money<Currency.MZE>
public typealias MZM = _Money<Currency.MZM>
public typealias MZN = _Money<Currency.MZN>
public typealias NAD = _Money<Currency.NAD>
public typealias NGN = _Money<Currency.NGN>
public typealias NIC = _Money<Currency.NIC>
public typealias NIO = _Money<Currency.NIO>
public typealias NLG = _Money<Currency.NLG>
public typealias NOK = _Money<Currency.NOK>
public typealias NPR = _Money<Currency.NPR>
public typealias NZD = _Money<Currency.NZD>
public typealias OMR = _Money<Currency.OMR>
public typealias PAB = _Money<Currency.PAB>
public typealias PEI = _Money<Currency.PEI>
public typealias PEN = _Money<Currency.PEN>
public typealias PES = _Money<Currency.PES>
public typealias PGK = _Money<Currency.PGK>
public typealias PHP = _Money<Currency.PHP>
public typealias PKR = _Money<Currency.PKR>
public typealias PLN = _Money<Currency.PLN>
public typealias PLZ = _Money<Currency.PLZ>
public typealias PTE = _Money<Currency.PTE>
public typealias PYG = _Money<Currency.PYG>
public typealias QAR = _Money<Currency.QAR>
public typealias RHD = _Money<Currency.RHD>
public typealias ROL = _Money<Currency.ROL>
public typealias RON = _Money<Currency.RON>
public typealias RSD = _Money<Currency.RSD>
public typealias RUB = _Money<Currency.RUB>
public typealias RUR = _Money<Currency.RUR>
public typealias RWF = _Money<Currency.RWF>
public typealias SAR = _Money<Currency.SAR>
public typealias SBD = _Money<Currency.SBD>
public typealias SCR = _Money<Currency.SCR>
public typealias SDD = _Money<Currency.SDD>
public typealias SDG = _Money<Currency.SDG>
public typealias SDP = _Money<Currency.SDP>
public typealias SEK = _Money<Currency.SEK>
public typealias SGD = _Money<Currency.SGD>
public typealias SHP = _Money<Currency.SHP>
public typealias SIT = _Money<Currency.SIT>
public typealias SKK = _Money<Currency.SKK>
public typealias SLL = _Money<Currency.SLL>
public typealias SOS = _Money<Currency.SOS>
public typealias SRD = _Money<Currency.SRD>
public typealias SRG = _Money<Currency.SRG>
public typealias SSP = _Money<Currency.SSP>
public typealias STD = _Money<Currency.STD>
public typealias SUR = _Money<Currency.SUR>
public typealias SVC = _Money<Currency.SVC>
public typealias SYP = _Money<Currency.SYP>
public typealias SZL = _Money<Currency.SZL>
public typealias THB = _Money<Currency.THB>
public typealias TJR = _Money<Currency.TJR>
public typealias TJS = _Money<Currency.TJS>
public typealias TMM = _Money<Currency.TMM>
public typealias TMT = _Money<Currency.TMT>
public typealias TND = _Money<Currency.TND>
public typealias TOP = _Money<Currency.TOP>
public typealias TPE = _Money<Currency.TPE>
public typealias TRL = _Money<Currency.TRL>
public typealias TRY = _Money<Currency.TRY>
public typealias TTD = _Money<Currency.TTD>
public typealias TWD = _Money<Currency.TWD>
public typealias TZS = _Money<Currency.TZS>
public typealias UAH = _Money<Currency.UAH>
public typealias UAK = _Money<Currency.UAK>
public typealias UGS = _Money<Currency.UGS>
public typealias UGX = _Money<Currency.UGX>
public typealias USD = _Money<Currency.USD>
public typealias USN = _Money<Currency.USN>
public typealias USS = _Money<Currency.USS>
public typealias UYI = _Money<Currency.UYI>
public typealias UYP = _Money<Currency.UYP>
public typealias UYU = _Money<Currency.UYU>
public typealias UZS = _Money<Currency.UZS>
public typealias VEB = _Money<Currency.VEB>
public typealias VEF = _Money<Currency.VEF>
public typealias VND = _Money<Currency.VND>
public typealias VNN = _Money<Currency.VNN>
public typealias VUV = _Money<Currency.VUV>
public typealias WST = _Money<Currency.WST>
public typealias XAF = _Money<Currency.XAF>
public typealias XAG = _Money<Currency.XAG>
public typealias XAU = _Money<Currency.XAU>
public typealias XBA = _Money<Currency.XBA>
public typealias XBB = _Money<Currency.XBB>
public typealias XBC = _Money<Currency.XBC>
public typealias XBD = _Money<Currency.XBD>
public typealias XCD = _Money<Currency.XCD>
public typealias XDR = _Money<Currency.XDR>
public typealias XEU = _Money<Currency.XEU>
public typealias XFO = _Money<Currency.XFO>
public typealias XFU = _Money<Currency.XFU>
public typealias XOF = _Money<Currency.XOF>
public typealias XPD = _Money<Currency.XPD>
public typealias XPF = _Money<Currency.XPF>
public typealias XPT = _Money<Currency.XPT>
public typealias XRE = _Money<Currency.XRE>
public typealias XSU = _Money<Currency.XSU>
public typealias XTS = _Money<Currency.XTS>
public typealias XUA = _Money<Currency.XUA>
public typealias XXX = _Money<Currency.XXX>
public typealias YDD = _Money<Currency.YDD>
public typealias YER = _Money<Currency.YER>
public typealias YUD = _Money<Currency.YUD>
public typealias YUM = _Money<Currency.YUM>
public typealias YUN = _Money<Currency.YUN>
public typealias YUR = _Money<Currency.YUR>
public typealias ZAL = _Money<Currency.ZAL>
public typealias ZAR = _Money<Currency.ZAR>
public typealias ZMK = _Money<Currency.ZMK>
public typealias ZMW = _Money<Currency.ZMW>
public typealias ZRN = _Money<Currency.ZRN>
public typealias ZRZ = _Money<Currency.ZRZ>
public typealias ZWL = _Money<Currency.ZWL>
public typealias ZWR = _Money<Currency.ZWR>
public typealias ZWD = _Money<Currency.ZWD>
