platform :ios do

  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: "Money-iOS",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
          
  end
  
end

platform :mac do
  
  desc "Runs all the tests"
  lane :test do

    scan(
      scheme: "Money-OSX",
      destination: "platform=macOS",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
    
  end
  
end
